<a href="https://colab.research.google.com/github/josephgalicinao/SkinLesionDetection/blob/main/Skin_Lesion_CNNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

Important imports and packages used

In [ ]:
from google.colab import userdata
import os

import kagglehub
import pandas as pd
import tensorflow as tf
import os
import csv
import numpy as np
import matplotlib.pyplot as plt
import cv2
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedGroupKFold
import torch
import transformers
import torchvision.transforms as T

from tqdm import tqdm
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc
from transformers import ViTForImageClassification, ViTImageProcessor, AutoConfig
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from transformers import Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from transformers import AutoModelForImageClassification, AutoImageProcessor

!pip install evaluate
import evaluate
import numpy as np
from sklearn.metrics import average_precision_score

# import selectkbest
from sklearn.feature_selection import SelectKBest, f_classif

IMG_SIZE   = (128, 128)
AUTOTUNE   = tf.data.AUTOTUNE

label_map = {'Benign': 0,
             'Malignant': 1}

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

ISIC 2018

In [ ]:
isic2018_path = kagglehub.dataset_download("josephgalicinao/isic-2018-dataset")
print("Path to dataset files:", isic2018_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-dataset/1.archive...

100%|██████████| 237M/237M [00:01<00:00, 202MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-dataset/versions/1

ISIC 2018 Test

In [ ]:
# Download latest version
isic2018_test_path = kagglehub.dataset_download("josephgalicinao/isic-2018-test-dataset")
print("Path to dataset files:", isic2018_test_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-test-dataset/1.archive...

100%|██████████| 37.3M/37.3M [00:00<00:00, 97.8MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-test-dataset/versions/1

Get the metadata of the datasets

In [ ]:
def get_train_isic2018():
  print("ISIC 2018 Training Dataset...")
  df = pd.read_csv(f"{isic2018_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values
  isic_patient_ids = df["lesion_id"].values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx)

  return isic_paths, isic_dx, isic_patient_ids

def get_test_isic2018():
  print("ISIC 2018 Test Dataset...")
  df = pd.read_csv(f"{isic2018_test_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_test_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx)

  return isic_paths, isic_dx

Make the straifier and k fold

In [ ]:
# Stratifier
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

## Evaluation Metrics

In [ ]:
def get_metrics(y_val, y_pred):
  # y_true: true labels, y_scores: predicted probabilities
  precision, recall, thresholds = precision_recall_curve(y_val, y_pred)
  pr_auc = auc(recall, precision)
  precision = precision_score(y_val, y_pred, average='binary')
  recall = recall_score(y_val, y_pred, average='binary')
  f1 = f1_score(y_val, y_pred, average='binary')

  return [precision, recall, f1, pr_auc]

# CNN-Based Transfer Learning

## Dataset

In [ ]:
# Dataset class
class SkinLesionDataset(Dataset):
    def __init__(self, labels, img_paths, transform=None):
        self.labels = labels
        self.img_paths = img_paths
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = Image.open(self.img_paths[idx]).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.long)

        if self.transform is not None:
            image = self.transform(image)

        return {
            "pixel_values": image,
            "labels": label,
        }

Oversample

In [ ]:
def oversample_minority(x_train, y_train, abcde=None, weights=None):
    x_train = np.array(x_train)
    y_train = np.array(y_train)

    # Oversample the minority class
    pos_features = x_train[y_train == 1] # Get the malignant images
    neg_features = x_train[y_train == 0] # Get the benign images

    pos_labels = y_train[y_train == 1] # Get the malignant labels
    neg_labels = y_train[y_train == 0] # Get the benign labels

    if abcde is not None:
      pos_abcde = abcde[y_train == 1] # Get the malignant abcde features
      neg_abcde = abcde[y_train == 0] # Get the benign abcde features

    if weights is not None:
      pos_weights = weights[y_train == 1] # Get the malignant weights
      neg_weights = weights[y_train == 0] # Get the benign weights

    ids = np.arange(len(pos_features)) # Create an array that goes from 0 - len(pos_features)
    choice = np.random.choice(ids, len(neg_features)) # Choose len(neg_features) number of ids
    oversampled_pos_features = pos_features[choice] # Oversample the minority class to get images
    oversampled_pos_labels = pos_labels[choice] # Oversample the minority class to get labels
    if abcde is not None:
      oversampled_pos_abcde = pos_abcde[choice] # Oversample the minority class to get abcde features
    if weights is not None:
      oversampled_pos_weights = pos_weights[choice] # Oversample the minority class to get weights

    x_train = np.concatenate([oversampled_pos_features, neg_features], axis=0) # Concatenate the data sets
    y_train = np.concatenate([oversampled_pos_labels, neg_labels], axis=0) # Concatenate the data set

    if abcde is not None:
      abcde = np.concatenate([oversampled_pos_abcde, neg_abcde], axis=0) # Concatenate the
    if weights is not None:
      weights = np.concatenate([oversampled_pos_weights, neg_weights], axis=0) # Concatenate the data sets

    order = np.arange(len(x_train)) # Create an array that goes from 0 - len(x_train)
    np.random.shuffle(order) # Shuffle the array
    x_train = x_train[order] # Shuffle the images
    y_train = y_train[order] # Shuffle the labels

    if abcde is not None:
      abcde = abcde[order] # Shuffle the abcde features
    if weights is not None:
      weights = weights[order] # Shuffle the weights

    return x_train, y_train, abcde, weights

batch = 64

## Metrics

In [ ]:
accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    probs = np.exp(logits) / np.exp(logits).sum(-1, keepdims=True)

    metrics = {}
    metrics.update(accuracy.compute(predictions=preds, references=labels))
    metrics.update(precision.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(recall.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(f1.compute(predictions=preds, references=labels, average="binary"))

    metrics["pr_auc"] = average_precision_score(labels, probs[:, 1])

    return metrics

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

## Preprocess

In [ ]:
def preprocess(image_processor):
  train_transform = T.Compose([
      T.Resize((224, 224)),
      T.RandomHorizontalFlip(p=0.5),
      T.RandomVerticalFlip(p=0.5),
      T.RandomApply([
          T.ColorJitter(
              brightness=0.1,
              contrast=0.1,
              saturation=0.1,
              hue=0.05
          )
      ], p=0.5),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
  ])

  val_transform = T.Compose([
      T.Resize((224, 224)),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
  ])

  return train_transform, val_transform

## ResNet50

Five-fold cross validation with different ratios of frozen vs. learnable layers are fine-tuned here

In [ ]:
model_name = "microsoft/resnet-50"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

for prop in [0.75, 0.5, 0.25, 0]:
  print(f"Prop: {prop}")
  for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
    train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
    train_dx, val_dx = dx[train_idx], dx[val_idx]
    train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

    # Get Preprocessed Data
    image_processor = AutoImageProcessor.from_pretrained(model_name)
    train_transform, val_transform = preprocess(image_processor)
    train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
    val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

    model = AutoModelForImageClassification.from_pretrained(
        model_name,
        num_labels=2,
        ignore_mismatched_sizes=True
    )

    # Replace classification head
    print(model.classifier)
    in_features = model.classifier[1].in_features

    model.classifier = torch.nn.Sequential(
        torch.nn.Flatten(),
        torch.nn.Linear(in_features, 128),
        torch.nn.ReLU(),
        torch.nn.Linear(128, 2)
    )

    # Freeze backbone
    for param in model.resnet.parameters():
        param.requires_grad = False

    # Collect ResNet stages
    stages = list(model.resnet.encoder.stages)

    # Unfreeze last proportion of stages
    n_stages = len(stages)
    n_unfreeze = max(1, int(n_stages * prop))  # avoid 0
    print(f"Unfrozen Stages: {n_unfreeze} / {n_stages}")

    for stage in stages[-n_unfreeze:]:
        for param in stage.parameters():
            param.requires_grad = True

    # Always train classifier
    for param in model.classifier.parameters():
        param.requires_grad = True

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    eval_results = trainer.evaluate()

    print(eval_results)

ISIC 2018 Training Dataset...
Prop: 0.75

KeyboardInterrupt:

Evaluate

Once determining that a proportion of 75% learnable and 25% frozen layers provided the optimal performance, we train on the full dataset.

In [ ]:
model_name = "microsoft/resnet-50"

prop = 0.75

train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

# Replace classification head
print(model.classifier)
in_features = model.classifier[1].in_features

model.classifier = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(in_features, 128),
    torch.nn.ReLU(),
    torch.nn.Linear(128, 2)
)

# Freeze backbone
for param in model.resnet.parameters():
    param.requires_grad = False

# Collect ResNet stages
stages = list(model.resnet.encoder.stages)

# Unfreeze last proportion of stages
n_stages = len(stages)
n_unfreeze = max(1, int(n_stages * prop))  # avoid 0
print(f"Unfrozen Stages: {n_unfreeze} / {n_stages}")

for stage in stages[-n_unfreeze:]:
    for param in stage.parameters():
        param.requires_grad = True

# Always train classifier
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=8,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

print(eval_results)

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

preprocessor_config.json:   0%|          | 0.00/266 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.6k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

model.safetensors: reconstructing file:   0%|          |  0.00B /  102MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/320 [00:00<?, ?it/s]

[transformers] ResNetForImageClassification LOAD REPORT from: microsoft/resnet-50
Key                 | Status   |
--------------------+----------+--------------------------------------------------------------------------------------------
classifier.1.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.1.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 2048]) vs model:torch.Size([2, 2048])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=2048, out_features=2, bias=True)
)
Unfrozen Stages: 3 / 4

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4526447653770447, 'eval_accuracy': 0.7579365079365079, 'eval_precision': 0.44939965694682676, 'eval_recall': 0.8534201954397395, 'eval_f1': 0.5887640449438202, 'eval_pr_auc': 0.6585211713665331}

## MobileNetV2

Five-fold cross validation with different ratios of frozen vs. learnable layers are fine-tuned here

In [ ]:
model_name = "google/mobilenet_v2_1.4_224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

for prop in [0.75, 0.5, 0.25, 0]:
  print(f"Prop: {prop}")
  for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
    train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
    train_dx, val_dx = dx[train_idx], dx[val_idx]
    train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

    # Get Preprocessed Data
    image_processor = AutoImageProcessor.from_pretrained(model_name)
    train_transform, val_transform = preprocess(image_processor)
    train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
    val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

    model = AutoModelForImageClassification.from_pretrained(
        model_name,
        num_labels=2,
        ignore_mismatched_sizes=True
    )

    # Replace classification head
    print(model.classifier)
    in_features = model.classifier.in_features

    model.classifier = torch.nn.Sequential(
        torch.nn.Flatten(),
        torch.nn.Linear(in_features, 128),
        torch.nn.ReLU(),
        torch.nn.Linear(128, 2)
    )

    # Freeze backbone
    for param in model.base_model.parameters():
      param.requires_grad = False

    # Collect MobileNetV2 stages
    blocks = list(model.base_model.layer)

    n_blocks = len(blocks)
    n_unfreeze = max(1, int(n_blocks * prop))

    print(f"Unfrozen Blocks: {n_unfreeze} / {n_blocks}")

    for block in blocks[-n_unfreeze:]:
        for param in block.parameters():
            param.requires_grad = True

    # Always train classifier
    for param in model.classifier.parameters():
        param.requires_grad = True

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    eval_results = trainer.evaluate()

    print(eval_results)

ISIC 2018 Training Dataset...
Prop: 0.75

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1001`.

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

[transformers] MobileNetV2ForImageClassification LOAD REPORT from: google/mobilenet_v2_1.4_224
Key               | Status   |
------------------+----------+--------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1001, 1792]) vs model:torch.Size([2, 1792])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1001]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Linear(in_features=1792, out_features=2, bias=True)
Unfrozen Blocks: 12 / 16

Evaluation

In [ ]:
model_name = "google/mobilenet_v2_1.4_224"

prop = 0.75
train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

with open('/content/drive/MyDrive/Thesis/isic2018_fine_mobilenetv2.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  # Get Preprocessed Data
  image_processor = AutoImageProcessor.from_pretrained(model_name)
  train_transform, val_transform = preprocess(image_processor)
  train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
  val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

  model = AutoModelForImageClassification.from_pretrained(
      model_name,
      num_labels=2,
      ignore_mismatched_sizes=True
  )

  # Replace classification head
  print(model.classifier)
  in_features = model.classifier.in_features

  model.classifier = torch.nn.Sequential(
      torch.nn.Flatten(),
      torch.nn.Linear(in_features, 128),
      torch.nn.ReLU(),
      torch.nn.Linear(128, 2)
  )

  # Freeze backbone
  for param in model.base_model.parameters():
    param.requires_grad = False

  # Collect MobileNetV2 stages
  blocks = list(model.base_model.layer)

  n_blocks = len(blocks)
  n_unfreeze = max(1, int(n_blocks * prop))

  print(f"Unfrozen Blocks: {n_unfreeze} / {n_blocks}")

  for block in blocks[-n_unfreeze:]:
      for param in block.parameters():
          param.requires_grad = True

  # Always train classifier
  for param in model.classifier.parameters():
      param.requires_grad = True

  # Train the model
  training_args = TrainingArguments(
      output_dir="./trains",
      per_device_train_batch_size=64,
      per_device_eval_batch_size=64,
      eval_strategy="epoch",
      save_strategy="epoch",
      logging_strategy="epoch",
      num_train_epochs=10,
      learning_rate=1e-5,
      save_total_limit=2,
      remove_unused_columns=False,
      load_best_model_at_end=True,
      metric_for_best_model="pr_auc",
      greater_is_better=True,
      dataloader_num_workers=8,
      dataloader_pin_memory=True,
      fp16=torch.cuda.is_available(),
      report_to="none",
      disable_tqdm=False,
  )

  trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics
  )

  trainer.train()

  eval_results = trainer.evaluate()

  print(eval_results)

  writer.writerow([
      prop,
      eval_results.get("eval_accuracy"),
      eval_results.get("eval_precision"),
      eval_results.get("eval_recall"),
      eval_results.get("eval_f1"),
      eval_results.get("eval_pr_auc"),
  ])

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

preprocessor_config.json:   0%|          | 0.00/406 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.8k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1001`.

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 24.7MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

[transformers] MobileNetV2ForImageClassification LOAD REPORT from: google/mobilenet_v2_1.4_224
Key               | Status   |
------------------+----------+--------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1001]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1001, 1792]) vs model:torch.Size([2, 1792])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Linear(in_features=1792, out_features=2, bias=True)
Unfrozen Blocks: 12 / 16

model.safetensors: reconstructing file:   0%|          |  0.00B / 24.7MB

model.safetensors: downloading bytes:           |  0.00B

## ConvNeXtTiny

Five-fold cross validation with different ratios of frozen vs. learnable layers are fine-tuned here

In [ ]:
model_name = "facebook/convnext-tiny-224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

for prop in [0.75, 0.5, 0.25, 0]:
  print(f"Prop: {prop}")
  for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
    train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
    train_dx, val_dx = dx[train_idx], dx[val_idx]
    train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

    # Get Preprocessed Data
    image_processor = AutoImageProcessor.from_pretrained(model_name)
    train_transform, val_transform = preprocess(image_processor)
    train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
    val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

    model = AutoModelForImageClassification.from_pretrained(
        model_name,
        num_labels=2,
        ignore_mismatched_sizes=True
    )

    # Replace classification head
    print(model.classifier)
    in_features = model.classifier.in_features

    model.classifier = torch.nn.Sequential(
        torch.nn.Flatten(),
        torch.nn.Linear(in_features, 128),
        torch.nn.ReLU(),
        torch.nn.Linear(128, 2)
    )

    # Freeze backbone
    for param in model.convnext.parameters():
      param.requires_grad = False

    # Collect MobileNetV2 stages
    blocks = list(model.convnext.encoder.stages)

    n_blocks = len(blocks)
    n_unfreeze = max(1, int(n_blocks * prop))

    print(f"Unfrozen Blocks: {n_unfreeze} / {n_blocks}")

    for block in blocks[-n_unfreeze:]:
        for param in block.parameters():
            param.requires_grad = True

    # Always train classifier
    for param in model.classifier.parameters():
        param.requires_grad = True

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    eval_results = trainer.evaluate()

    print(eval_results)

ISIC 2018 Training Dataset...
Prop: 0.75

preprocessor_config.json:   0%|          | 0.00/266 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.6k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  114MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/182 [00:00<?, ?it/s]

[transformers] ConvNextForImageClassification LOAD REPORT from: facebook/convnext-tiny-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Linear(in_features=768, out_features=2, bias=True)
Unfrozen Blocks: 3 / 4

model.safetensors: reconstructing file:   0%|          |  0.00B /  114MB

model.safetensors: downloading bytes:           |  0.00B

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Exception ignored in sys.unraisablehook
Exception ignored in sys.unraisablehook: : <built-in function unraisablehook><built-in function unraisablehook>
Traceback (most recent call last):

KeyboardInterrupt:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/ipykernel/iostream.py", line 561, in write
  File "/usr/local/lib/python3.13/dist-packages/ipykernel/iostream.py", line 561, in write
        self.pub_thread.schedule(self._flush)self.pub_thread.schedule(self._flush)

  File "/usr/local/lib/python3.13/dist-packages/ipykernel/iostream.py", line 212, in schedule
  File "/usr/local/lib/python3.13/dist-packages/ipykernel/iostream.py", line 212, in schedule
Exception in thread Thread-7 (_pin_memory_loop):
        f()f()Exception ignored in atexit callback <function _exit_function at 0x7ff6216e0540>
:
  File "/usr/local/lib/python3.13/dist-packages/ipykernel/iostream.py", line 518, in _flush

    self.session.send(Traceback (most recent call last):

Evaluate

Once determining that a proportion of 75% learnable and 25% frozen layers provided the optimal performance, we train on the full dataset.

In [ ]:
model_name = "facebook/convnext-tiny-224"

prop = 0.75
train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

# Replace classification head
print(model.classifier)
in_features = model.classifier.in_features

model.classifier = torch.nn.Sequential(
    torch.nn.Flatten(),
    torch.nn.Linear(in_features, 128),
    torch.nn.ReLU(),
    torch.nn.Linear(128, 2)
)

# Freeze backbone
for param in model.convnext.parameters():
  param.requires_grad = False

# Collect MobileNetV2 stages
blocks = list(model.convnext.encoder.stages)

n_blocks = len(blocks)
n_unfreeze = max(1, int(n_blocks * prop))

print(f"Unfrozen Blocks: {n_unfreeze} / {n_blocks}")

for block in blocks[-n_unfreeze:]:
    for param in block.parameters():
        param.requires_grad = True

# Always train classifier
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=8,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

writer.writerow([
    prop,
    eval_results.get("eval_accuracy"),
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
])

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

Loading weights:   0%|          | 0/182 [00:00<?, ?it/s]

[transformers] ConvNextForImageClassification LOAD REPORT from: facebook/convnext-tiny-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Linear(in_features=768, out_features=2, bias=True)
Unfrozen Blocks: 3 / 4

KeyboardInterrupt: