<a href="https://colab.research.google.com/github/josephgalicinao/SkinLesionDetection/blob/main/Skin_Lesion_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

Important imports and packages used

In [ ]:
!pip install fairlearn
# !pip install numpy==2.4.4 pandas==3.0.2 scikit-learn==1.8.0
# !pip install --upgrade --force-reinstall --no-cache-dir numpy scikit-learn
!pip install evaluate

# from google .colab import userdata
import os
import kagglehub
import pandas as pd
import os
import csv
import numpy as np
import torch
import transformers
import torchvision.transforms as T
# import sklearn
import evaluate

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve, auc
from transformers import ViTForImageClassification, ViTImageProcessor, AutoConfig
from torch.utils.data import Dataset, DataLoader
from transformers import Trainer, TrainingArguments
from transformers import AutoModelForImageClassification, AutoImageProcessor
from PIL import Image

IMG_SIZE   = (128, 128)

label_map = {'Benign': 0,
             'Malignant': 1}

Collecting fairlearn
  Downloading fairlearn-0.15.0-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: narwhals>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from fairlearn) (2.26.0)
Requirement already satisfied: numpy>=1.24.4 in /usr/local/lib/python3.13/dist-packages (from fairlearn) (2.1.3)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.13/dist-packages (from fairlearn) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from fairlearn) (1.6.1)
Requirement already satisfied: scipy>=1.9.3 in /usr/local/lib/python3.13/dist-packages (from fairlearn) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.3->fairlearn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.3->fairlearn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0.3->fairlearn) (2026.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->fairlearn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->fairlearn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.6.0->fairlearn) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->fairlearn) (1.17.0)
Downloading fairlearn-0.15.0-py3-none-any.whl (141 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.4/141.4 kB 5.2 MB/s eta 0:00:00
Installing collected packages: fairlearn
Successfully installed fairlearn-0.15.0
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.7 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

ISIC 2018

In [ ]:
isic2018_path = kagglehub.dataset_download("josephgalicinao/isic-2018-dataset")

print("Path to dataset files:", isic2018_path)

Using Colab cache for faster access to the 'isic-2018-dataset' dataset.
Path to dataset files: /kaggle/input/isic-2018-dataset

ISIC 2018 Test

In [ ]:
# Download latest version
isic2018_test_path = kagglehub.dataset_download("josephgalicinao/isic-2018-test-dataset")

print("Path to dataset files:", isic2018_test_path)

Using Colab cache for faster access to the 'isic-2018-test-dataset' dataset.
Path to dataset files: /kaggle/input/isic-2018-test-dataset

Milk10K + ISIC Archive

In [ ]:
skin_tone_path = kagglehub.dataset_download("josephgalicinao/representative-dataset")

print("Path to dataset files:", skin_tone_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/representative-dataset/1.archive...

100%|██████████| 8.03G/8.03G [00:46<00:00, 187MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/representative-dataset/versions/1

## Create Datasets

Create Fitzpatrick dataset + Unlabeled Fitzpatrick

In [ ]:
def get_fitzpatrick_datasets():
  # ISIC Archive
  print("Getting ISIC...")
  df = pd.read_csv(f"{skin_tone_path}/Representative/ISIC_archive/isic_metadata.csv")
  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0}).values
  isic_skin_tone = df["fitzpatrick_skin_type"].map({'I': 0, 'II': 0, 'III': 1,
                                                         'IV': 1, 'V': 2, 'VI': 2}).values
  isic_patient_ids = df["patient_id"].values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{skin_tone_path}/Representative/ISIC_archive/{isic_id}.jpg")

  # Dataset characteristics
  print("----- ISIC -----")
  print(f"Number images: {len(isic_paths)}")
  print(f"Number malignant images: {np.sum(isic_dx == 1)}")
  print(f"Number benign images: {np.sum(isic_dx == 0)}")
  unique, counts = np.unique(isic_skin_tone, return_counts=True)
  for i in range(len(unique)):
    print(f"Number images with skin tone {unique[i]}: {counts[i]}")

  assert len(isic_paths) == len(isic_ids) == len(isic_dx) == len(isic_skin_tone) == len(isic_patient_ids)

  # MILK
  print("Getting MILK...")
  df = pd.read_csv(f"{skin_tone_path}/Representative/Milk10K/metadata.csv")
  # Remove rows where dx is NaN or Indeterminate
  df = df.dropna(subset=['diagnosis_1'])
  df = df[df['diagnosis_1'] != 'Indeterminate']

  milk_ids = df["isic_id"].values
  milk_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0}).values
  milk_skin_tone = df["skin_tone_class"].map({5: 0, 4: 0, 3: 1, 2: 1, 1: 2, 0: 2}).values
  milk_patient_ids = df["lesion_id"].values

  milk_paths = []
  for milk_id in milk_ids:
    milk_paths.append(f"{skin_tone_path}/Representative/Milk10K/images/{milk_id}.jpg")

  # print("----- MILK -----")
  print(f"Number images: {len(milk_paths)}")
  print(f"Number malignant images: {np.sum(milk_dx == 1)}")
  print(f"Number benign images: {np.sum(milk_dx == 0)}")
  print(f"Number skin tones: {np.unique(milk_skin_tone)}")
  unique, counts = np.unique(milk_skin_tone, return_counts=True)
  for i in range(len(unique)):
    print(f"Number images with skin tone {unique[i]}: {counts[i]}")

  assert len(milk_paths) == len(milk_ids) == len(milk_dx) == len(milk_skin_tone) == len(milk_patient_ids)

  print("Combining Datasets...")
  paths = np.concatenate((isic_paths, milk_paths))
  dx = np.concatenate((isic_dx, milk_dx))
  skin_tone = np.concatenate((isic_skin_tone, milk_skin_tone))
  patient_ids = np.concatenate((isic_patient_ids, milk_patient_ids))

  print("---- Combined Datasets -----")
  print(f"Number images: {len(paths)}")
  print(f"Number malignant images: {np.sum(dx == 1)}")
  print(f"Number benign images: {np.sum(dx == 0)}")
  unique, counts = np.unique(skin_tone, return_counts=True)
  for i in range(len(unique)):
    print(f"Number images with skin tone {unique[i]}: {counts[i]}")

  assert len(paths) == len(dx) == len(skin_tone)== len(patient_ids)

  return paths, dx, skin_tone, patient_ids

def get_train_isic2018():
  print("ISIC 2018 Training Dataset...")
  df = pd.read_csv(f"{isic2018_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values
  isic_patient_ids = df["lesion_id"].values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx)

  return isic_paths, isic_dx, isic_patient_ids

def get_test_isic2018():
  print("ISIC 2018 Test Dataset...")
  df = pd.read_csv(f"{isic2018_test_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_test_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx)

  return isic_paths, isic_dx

Oversampling method

In [ ]:
def oversample_minority(x_train, y_train, abcde=None, weights=None):
    x_train = np.array(x_train)
    y_train = np.array(y_train)

    # Oversample the minority class
    pos_features = x_train[y_train == 1] # Get the malignant images
    neg_features = x_train[y_train == 0] # Get the benign images

    pos_labels = y_train[y_train == 1] # Get the malignant labels
    neg_labels = y_train[y_train == 0] # Get the benign labels

    if abcde is not None:
      pos_abcde = abcde[y_train == 1] # Get the malignant abcde features
      neg_abcde = abcde[y_train == 0] # Get the benign abcde features

    if weights is not None:
      pos_weights = weights[y_train == 1] # Get the malignant weights
      neg_weights = weights[y_train == 0] # Get the benign weights

    ids = np.arange(len(pos_features)) # Create an array that goes from 0 - len(pos_features)
    choice = np.random.choice(ids, len(neg_features)) # Choose len(neg_features) number of ids
    oversampled_pos_features = pos_features[choice] # Oversample the minority class to get images
    oversampled_pos_labels = pos_labels[choice] # Oversample the minority class to get labels
    if abcde is not None:
      oversampled_pos_abcde = pos_abcde[choice] # Oversample the minority class to get abcde features
    if weights is not None:
      oversampled_pos_weights = pos_weights[choice] # Oversample the minority class to get weights

    x_train = np.concatenate([oversampled_pos_features, neg_features], axis=0) # Concatenate the data sets
    y_train = np.concatenate([oversampled_pos_labels, neg_labels], axis=0) # Concatenate the data set

    if abcde is not None:
      abcde = np.concatenate([oversampled_pos_abcde, neg_abcde], axis=0) # Concatenate the
    if weights is not None:
      weights = np.concatenate([oversampled_pos_weights, neg_weights], axis=0) # Concatenate the data sets

    order = np.arange(len(x_train)) # Create an array that goes from 0 - len(x_train)
    np.random.shuffle(order) # Shuffle the array
    x_train = x_train[order] # Shuffle the images
    y_train = y_train[order] # Shuffle the labels

    if abcde is not None:
      abcde = abcde[order] # Shuffle the abcde features
    if weights is not None:
      weights = weights[order] # Shuffle the weights

    return x_train, y_train, abcde, weights

batch = 64

Image preprocessing

In [ ]:
def preprocess(image_processor):
  train_transform = T.Compose([
      T.Resize((224, 224)),
      T.RandomHorizontalFlip(p=0.5),
      T.RandomVerticalFlip(p=0.5),
      T.RandomApply([
          T.ColorJitter(
              brightness=0.1,
              contrast=0.1,
              saturation=0.1,
              hue=0.05
          )
      ], p=0.5),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
  ])

  val_transform = T.Compose([
      T.Resize((224, 224)),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
  ])

  return train_transform, val_transform

# Transformers

### Init

In [ ]:
# Stratifier
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Dataset class
class SkinLesionDataset(Dataset):
    def __init__(self, labels, img_paths, transform=None):
        self.labels = labels
        self.img_paths = img_paths
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = Image.open(self.img_paths[idx]).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.long)

        if self.transform is not None:
            image = self.transform(image)

        return {
            "pixel_values": image,
            "labels": label,
        }

### Metrics

In [ ]:
accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    probs = np.exp(logits) / np.exp(logits).sum(-1, keepdims=True)

    metrics = {}
    metrics.update(accuracy.compute(predictions=preds, references=labels))
    metrics.update(precision.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(recall.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(f1.compute(predictions=preds, references=labels, average="binary"))

    metrics["pr_auc"] = average_precision_score(labels, probs[:, 1])

    return metrics

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

## ISIC 2018

In this section, we train each model on the ISIC 2018 dataset. To fine tune the proportion of frozen to learnable layers, we employ five-fold cross-validation.

### ViT

Fine tune

In [ ]:
model_name = "google/vit-base-patch16-224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('./isic2018_fine_tuning_vit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for prop in [0.75, 0.5, 0.25, 0]:
    print(f"Prop: {prop}")
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
      train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
      train_dx, val_dx = dx[train_idx], dx[val_idx]
      train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

      # Get Preprocessed Data
      image_processor = AutoImageProcessor.from_pretrained(model_name)
      train_transform, val_transform = preprocess(image_processor)
      train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
      val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

      model = AutoModelForImageClassification.from_pretrained(
          model_name,
          num_labels=2,
          ignore_mismatched_sizes=True
      )

      # Freeze the whole ViT backbone first
      for param in model.vit.parameters():
          param.requires_grad = False

      layers = model.vit.encoder.layer
      n_layers = len(layers)
      print(f"Number of layers: {n_layers}")
      n_unfreeze = max(1, int(n_layers * prop))

      for layer in layers[-n_unfreeze:]:
          for param in layer.parameters():
              param.requires_grad = True

      # Keep classifier trainable
      for param in model.classifier.parameters():
          param.requires_grad = True

      # Train the model
      training_args = TrainingArguments(
          output_dir="./trains",
          per_device_train_batch_size=64,
          per_device_eval_batch_size=64,
          eval_strategy="epoch",
          save_strategy="epoch",
          logging_strategy="epoch",
          num_train_epochs=10,
          learning_rate=1e-5,
          save_total_limit=2,
          remove_unused_columns=False,
          load_best_model_at_end=True,
          metric_for_best_model="pr_auc",
          greater_is_better=True,
          dataloader_num_workers=8,
          dataloader_pin_memory=True,
          fp16=torch.cuda.is_available(),
          report_to="none",
          disable_tqdm=False,
      )

      trainer = Trainer(
          model=model,
          args=training_args,
          train_dataset=train_ds,
          eval_dataset=val_ds,
          compute_metrics=compute_metrics
      )

      trainer.train()

      eval_results = trainer.evaluate()

      print(eval_results)

      writer.writerow([
          prop,
          eval_results.get("eval_accuracy"),
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
      ])

ISIC 2018 Training Dataset...

NameError: name 'isic2018_path' is not defined

Evaluation Results (prop = 0.75)

In [ ]:
model_name = "google/vit-base-patch16-224"

train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.75

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

# Freeze the whole ViT backbone first
for param in model.vit.parameters():
    param.requires_grad = False

layers = model.vit.layers
n_layers = len(layers)
print(f"Number of layers: {n_layers}")
n_unfreeze = max(1, int(n_layers * prop))

for layer in layers[-n_unfreeze:]:
    for param in layer.parameters():
        param.requires_grad = True

# Keep classifier trainable
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=8,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

print(eval_results)

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

[transformers] ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Exception in thread Thread-5 (_pin_memory_loop):

KeyboardInterrupt:

### Swin Transformers

Fine Tuning

In [ ]:
model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('./isic2018_fine_tuning_swin.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])
  for prop in [0.75, 0.5, 0.25, 0]:
    print(f"Prop: {prop}")
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
      train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
      train_dx, val_dx = dx[train_idx], dx[val_idx]
      train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

      # Get Preprocessed Data
      image_processor = AutoImageProcessor.from_pretrained(model_name)
      train_transform, val_transform = preprocess(image_processor)
      train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
      val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

      model = AutoModelForImageClassification.from_pretrained(
          model_name,
          num_labels=2,
          ignore_mismatched_sizes=True
      )

      for param in model.swin.parameters():
          param.requires_grad = False

      # Flatten all blocks across stages
      all_blocks = []
      for stage in model.swin.encoder.layers:
          all_blocks.extend(stage.blocks)  # 'blocks' contains the transformer blocks

      n_blocks = len(all_blocks)
      print(f"Number of transformer blocks: {n_blocks}")

      n_unfreeze = max(1, int(n_blocks * prop))  # e.g., prop=0.25
      for block in all_blocks[-n_unfreeze:]:
          for param in block.parameters():
              param.requires_grad = True

      # Keep classifier trainable
      for param in model.classifier.parameters():
          param.requires_grad = True

      # Train the model
      training_args = TrainingArguments(
          output_dir="./trains",
          per_device_train_batch_size=64,
          per_device_eval_batch_size=64,
          eval_strategy="epoch",
          save_strategy="epoch",
          logging_strategy="epoch",
          num_train_epochs=10,
          learning_rate=1e-5,
          save_total_limit=2,
          remove_unused_columns=False,
          load_best_model_at_end=True,
          metric_for_best_model="pr_auc",
          greater_is_better=True,
          dataloader_num_workers=8,
          dataloader_pin_memory=True,
          fp16=torch.cuda.is_available(),
          report_to="none",
          disable_tqdm=False,
      )

      trainer = Trainer(
          model=model,
          args=training_args,
          train_dataset=train_ds,
          eval_dataset=val_ds,
          compute_metrics=compute_metrics
      )

      trainer.train()

      eval_results = trainer.evaluate()

      print(eval_results)

      writer.writerow([model_name] + [
          prop,
          eval_results.get("eval_accuracy"),
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
      ])

ISIC 2018 Training Dataset...
Prop: 0.75

preprocessor_config.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

The image processor of type `ViTImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/437M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.5281139612197876, 'eval_accuracy': 0.88598694123556, 'eval_precision': 0.7338935574229691, 'eval_recall': 0.6649746192893401, 'eval_f1': 0.6977363515312917, 'eval_pr_auc': 0.7742517062100615, 'eval_runtime': 1.3419, 'eval_samples_per_second': 1483.737, 'eval_steps_per_second': 23.847, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.42853212356567383, 'eval_accuracy': 0.87943971985993, 'eval_precision': 0.6955445544554455, 'eval_recall': 0.7042606516290727, 'eval_f1': 0.6998754669987547, 'eval_pr_auc': 0.7912885514261356, 'eval_runtime': 1.3284, 'eval_samples_per_second': 1504.803, 'eval_steps_per_second': 24.089, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4222662150859833, 'eval_accuracy': 0.8867552929591335, 'eval_precision': 0.7318611987381703, 'eval_recall': 0.6153846153846154, 'eval_f1': 0.6685878962536023, 'eval_pr_auc': 0.7783904867759949, 'eval_runtime': 1.359, 'eval_samples_per_second': 1494.434, 'eval_steps_per_second': 23.546, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.36623620986938477, 'eval_accuracy': 0.9029175050301811, 'eval_precision': 0.8012048192771084, 'eval_recall': 0.6768447837150128, 'eval_f1': 0.7337931034482759, 'eval_pr_auc': 0.8033533207770431, 'eval_runtime': 1.3459, 'eval_samples_per_second': 1477.068, 'eval_steps_per_second': 23.776, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4024829864501953, 'eval_accuracy': 0.8833499501495513, 'eval_precision': 0.7211267605633803, 'eval_recall': 0.6547314578005116, 'eval_f1': 0.6863270777479893, 'eval_pr_auc': 0.7806954715740192, 'eval_runtime': 1.3471, 'eval_samples_per_second': 1489.101, 'eval_steps_per_second': 23.754, 'epoch': 10.0}
Prop: 0.5

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.423344224691391, 'eval_accuracy': 0.8839779005524862, 'eval_precision': 0.7184986595174263, 'eval_recall': 0.6802030456852792, 'eval_f1': 0.6988265971316818, 'eval_pr_auc': 0.77663640491895, 'eval_runtime': 1.3272, 'eval_samples_per_second': 1500.178, 'eval_steps_per_second': 24.111, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.36758002638816833, 'eval_accuracy': 0.8824412206103052, 'eval_precision': 0.7060301507537688, 'eval_recall': 0.7042606516290727, 'eval_f1': 0.7051442910915935, 'eval_pr_auc': 0.7774599965194694, 'eval_runtime': 1.357, 'eval_samples_per_second': 1473.142, 'eval_steps_per_second': 23.582, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3448379635810852, 'eval_accuracy': 0.8887247661250616, 'eval_precision': 0.7126760563380282, 'eval_recall': 0.6710875331564987, 'eval_f1': 0.6912568306010929, 'eval_pr_auc': 0.7656867413134495, 'eval_runtime': 1.3637, 'eval_samples_per_second': 1489.293, 'eval_steps_per_second': 23.465, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3516921103000641, 'eval_accuracy': 0.8903420523138833, 'eval_precision': 0.7108433734939759, 'eval_recall': 0.7506361323155216, 'eval_f1': 0.7301980198019802, 'eval_pr_auc': 0.7898872775647234, 'eval_runtime': 1.3385, 'eval_samples_per_second': 1485.3, 'eval_steps_per_second': 23.908, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3513525426387787, 'eval_accuracy': 0.8848454636091725, 'eval_precision': 0.7105263157894737, 'eval_recall': 0.690537084398977, 'eval_f1': 0.7003891050583657, 'eval_pr_auc': 0.7824059138964129, 'eval_runtime': 1.335, 'eval_samples_per_second': 1502.625, 'eval_steps_per_second': 23.97, 'epoch': 10.0}
Prop: 0.25

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3387470841407776, 'eval_accuracy': 0.8749372174786539, 'eval_precision': 0.6730310262529833, 'eval_recall': 0.7157360406091371, 'eval_f1': 0.6937269372693727, 'eval_pr_auc': 0.7646370478428369, 'eval_runtime': 1.3695, 'eval_samples_per_second': 1453.812, 'eval_steps_per_second': 23.366, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3208940625190735, 'eval_accuracy': 0.8774387193596799, 'eval_precision': 0.6833333333333333, 'eval_recall': 0.7192982456140351, 'eval_f1': 0.7008547008547008, 'eval_pr_auc': 0.7529645076398753, 'eval_runtime': 1.3603, 'eval_samples_per_second': 1469.499, 'eval_steps_per_second': 23.524, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.30539846420288086, 'eval_accuracy': 0.8744460856720827, 'eval_precision': 0.641860465116279, 'eval_recall': 0.7320954907161804, 'eval_f1': 0.6840148698884758, 'eval_pr_auc': 0.7582171831328188, 'eval_runtime': 1.3565, 'eval_samples_per_second': 1497.192, 'eval_steps_per_second': 23.589, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.31833696365356445, 'eval_accuracy': 0.8752515090543259, 'eval_precision': 0.6552462526766595, 'eval_recall': 0.7786259541984732, 'eval_f1': 0.7116279069767442, 'eval_pr_auc': 0.7765111428924063, 'eval_runtime': 1.3576, 'eval_samples_per_second': 1464.382, 'eval_steps_per_second': 23.572, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.31152021884918213, 'eval_accuracy': 0.8753738783649053, 'eval_precision': 0.6643356643356644, 'eval_recall': 0.7289002557544757, 'eval_f1': 0.6951219512195121, 'eval_pr_auc': 0.7650167437228995, 'eval_runtime': 1.3501, 'eval_samples_per_second': 1485.864, 'eval_steps_per_second': 23.703, 'epoch': 10.0}
Prop: 0

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.34915101528167725, 'eval_accuracy': 0.8352586639879458, 'eval_precision': 0.5589285714285714, 'eval_recall': 0.7944162436548223, 'eval_f1': 0.6561844863731656, 'eval_pr_auc': 0.743414503906311, 'eval_runtime': 1.3433, 'eval_samples_per_second': 1482.159, 'eval_steps_per_second': 23.822, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.34875252842903137, 'eval_accuracy': 0.8319159579789895, 'eval_precision': 0.5544041450777202, 'eval_recall': 0.8045112781954887, 'eval_f1': 0.656441717791411, 'eval_pr_auc': 0.7303931378649392, 'eval_runtime': 1.3457, 'eval_samples_per_second': 1485.5, 'eval_steps_per_second': 23.78, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3312586843967438, 'eval_accuracy': 0.8522895125553914, 'eval_precision': 0.573055028462998, 'eval_recall': 0.8010610079575596, 'eval_f1': 0.668141592920354, 'eval_pr_auc': 0.7246238473360654, 'eval_runtime': 1.347, 'eval_samples_per_second': 1507.845, 'eval_steps_per_second': 23.757, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.34759601950645447, 'eval_accuracy': 0.8385311871227364, 'eval_precision': 0.5596026490066225, 'eval_recall': 0.8600508905852418, 'eval_f1': 0.6780341023069207, 'eval_pr_auc': 0.7633013251830364, 'eval_runtime': 1.3469, 'eval_samples_per_second': 1475.997, 'eval_steps_per_second': 23.758, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.31073781847953796, 'eval_accuracy': 0.8569292123629113, 'eval_precision': 0.6027667984189723, 'eval_recall': 0.7800511508951407, 'eval_f1': 0.6800445930880713, 'eval_pr_auc': 0.754729339731909, 'eval_runtime': 1.3684, 'eval_samples_per_second': 1465.966, 'eval_steps_per_second': 23.385, 'epoch': 10.0}
Prop: 0.75

preprocessor_config.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/199M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

model.safetensors:   0%|          | 0.00/199M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

Evaluate

In [ ]:
model_name = "microsoft/swin-tiny-patch4-window7-224"
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference


train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.75

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

for param in model.swin.parameters():
    param.requires_grad = False

# Flatten all blocks across stages
all_blocks = []
for stage in model.swin.encoder.layers:
    all_blocks.extend(stage.blocks)  # 'blocks' contains the transformer blocks

n_blocks = len(all_blocks)
print(f"Number of transformer blocks: {n_blocks}")

n_unfreeze = max(1, int(n_blocks * prop))  # e.g., prop=0.25
for block in all_blocks[-n_unfreeze:]:
    for param in block.parameters():
        param.requires_grad = True

# Keep classifier trainable
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=8,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

print(eval_results)

writer.writerow([model_name] + [
    prop,
    eval_results.get("eval_accuracy"),
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
])

# Now evaluate on the combined dataset
img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

val_imgs = img_paths[val_idx]
val_dx = dx[val_idx]
val_skin_tones = skin_tones[val_idx]
val_patient_ids = patient_ids[val_idx]

# Get the results for the light, medium, and dark datasets
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)
val_results = trainer.predict(val_ds)

val_pred = np.argmax(val_results.predictions, axis=1)
val_dx = np.array(val_dx)

val_results = trainer.evaluate(eval_dataset=val_ds)
print(val_results)

# equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
# demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
# equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

# # Failsafe in case the runtime breaks
# print("Equal Opportunity:", equal_opportunity)
# print("Demographic Parity:", demographic_parity)
# print("Equalized Odds:", equalized_odds)

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

preprocessor_config.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/71.8k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

model.safetensors: reconstructing file:   0%|          |  0.00B /  113MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/221 [00:00<?, ?it/s]

[transformers] SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

KeyboardInterrupt:

### DeiT

Fine Tuning

In [ ]:
model_name = "facebook/deit-tiny-patch16-224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('./isic2018_fine_tuning_deit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Model", "Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for prop in [0.75, 0.5, 0.25, 0]:
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
      train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
      train_dx, val_dx = dx[train_idx], dx[val_idx]
      train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

      # Get Preprocessed Data
      image_processor = AutoImageProcessor.from_pretrained(model_name)
      train_transform, val_transform = preprocess(image_processor)
      train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
      val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

      print(f"Prop: {prop}")
      model = AutoModelForImageClassification.from_pretrained(
          model_name,
          num_labels=2,
          ignore_mismatched_sizes=True
      )

      # Freeze the whole ViT backbone first
      for param in model.vit.parameters():
          param.requires_grad = False

      layers = model.vit.layers
      n_layers = len(layers)
      print(f"Number of layers: {n_layers}")
      n_unfreeze = max(1, int(n_layers * prop))

      for layer in layers[-n_unfreeze:]:
          for param in layer.parameters():
              param.requires_grad = True

      # Keep classifier trainable
      for param in model.classifier.parameters():
          param.requires_grad = True

      # Train the model
      training_args = TrainingArguments(
          output_dir="./trains",
          per_device_train_batch_size=64,
          per_device_eval_batch_size=64,
          eval_strategy="epoch",
          save_strategy="epoch",
          logging_strategy="epoch",
          num_train_epochs=10,
          learning_rate=1e-5,
          save_total_limit=2,
          remove_unused_columns=False,
          load_best_model_at_end=True,
          metric_for_best_model="pr_auc",
          greater_is_better=True,
          dataloader_num_workers=0,
          dataloader_pin_memory=True,
          fp16=torch.cuda.is_available(),
          report_to="none",
          disable_tqdm=False,
      )

      trainer = Trainer(
          model=model,
          args=training_args,
          train_dataset=train_ds,
          eval_dataset=val_ds,
          compute_metrics=compute_metrics
      )

      trainer.train()

      eval_results = trainer.evaluate()

      print(eval_results)

      writer.writerow([
          model_name,
          prop,
          eval_results.get("eval_accuracy"),
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
      ])

ISIC 2018 Training Dataset...
Prop: 0.75

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

[transformers] ViTForImageClassification LOAD REPORT from: facebook/deit-tiny-patch16-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 192]) vs model:torch.Size([2, 192])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

ValueError: too many values to unpack (expected 2)

Evaluate

In [ ]:
model_name = "facebook/deit-tiny-patch16-224"

train_imgs, train_dx, _ = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.75

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

print(f"Prop: {prop}")
model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

# Freeze the whole ViT backbone first
for param in model.vit.parameters():
    param.requires_grad = False

layers = model.vit.layers
n_layers = len(layers)
print(f"Number of layers: {n_layers}")
n_unfreeze = max(1, int(n_layers * prop))

for layer in layers[-n_unfreeze:]:
    for param in layer.parameters():
        param.requires_grad = True

# Keep classifier trainable
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=0,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

print(eval_results)

writer.writerow([
    model_name,
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
])

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/69.6k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

Prop: 0.75

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 23.0MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

[transformers] ViTForImageClassification LOAD REPORT from: facebook/deit-tiny-patch16-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 192]) vs model:torch.Size([2, 192])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

model.safetensors: reconstructing file:   0%|          |  0.00B / 22.9MB

model.safetensors: downloading bytes:           |  0.00B

KeyboardInterrupt:

# Fairness Regularization

## Curated Dataset

We found that the Swin-Tiny Transformer architecutre provided the best performance on the ISIC 2018 dataset compared to the classical, CNN, and other transformer appraoches. Therefore, we employ this architecture when performing fairness regularization.

### Swin Transformer (no fariness regularization)

In this section, we perform no fairness regularization

In [ ]:
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

assert set(train_patient_ids).isdisjoint(set(val_patient_ids)) # Verifies that there is no data leakage

print("Train:", len(train_imgs))
print("Val:", len(val_imgs))
print("No patient overlap across splits.")

prop = 0.75

# Get Preprocessed Data
image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

model = AutoModelForImageClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)

for param in model.swin.parameters():
    param.requires_grad = False

# Flatten all blocks across stages
all_blocks = []
for stage in model.swin.encoder.layers:
    all_blocks.extend(stage.blocks)  # 'blocks' contains the transformer blocks

n_blocks = len(all_blocks)
print(f"Number of transformer blocks: {n_blocks}")

n_unfreeze = max(1, int(n_blocks * prop))  # e.g., prop=0.25
for block in all_blocks[-n_unfreeze:]:
    for param in block.parameters():
        param.requires_grad = True

# Keep classifier trainable
for param in model.classifier.parameters():
    param.requires_grad = True

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=0,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

eval_results = trainer.evaluate()

print(eval_results)

writer.writerow([model_name] + [
    prop,
    eval_results.get("eval_accuracy"),
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
])

# Get predictions
val_pred = np.argmax(eval_results.predictions, axis=1)
val_dx = np.array(val_dx)

equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

# Failsafe in case the runtime breaks
print("Equal Opportunity:", equal_opportunity)
print("Demographic Parity:", demographic_parity)
print("Equalized Odds:", equalized_odds)

Getting ISIC...
----- ISIC -----
Number images: 10121
Number malignant images: 2066
Number benign images: 8055
Number images with skin tone 0: 6012
Number images with skin tone 1: 2538
Number images with skin tone 2: 1571
Getting MILK...
Number images: 10234
Number malignant images: 7268
Number benign images: 2966
Number skin tones: [0 1 2]
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...
---- Combined Datasets -----
Number images: 20355
Number malignant images: 9334
Number benign images: 11021
Number images with skin tone 0: 8878
Number images with skin tone 1: 9722
Number images with skin tone 2: 1755
Train: 16284
Val: 4071
No patient overlap across splits.

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

Loading weights:   0%|          | 0/221 [00:00<?, ?it/s]

[transformers] SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

KeyboardInterrupt:

### Swin Transformer + Adversarial Network

#### Gradient Reversal Layer

In [ ]:
from torch.autograd import Function
import torch

class GradReverse(Function):
    @staticmethod
    def forward(ctx, x, lambda_):
        ctx.lambda_ = lambda_
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.lambda_ * grad_output, None

def grad_reverse(x, lambda_=1.0):
    return GradReverse.apply(x, lambda_)

#### Metrics

In [ ]:
!pip install evaluate
import evaluate
import numpy as np
from sklearn.metrics import average_precision_score

accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")
mae = evaluate.load("mae")

def compute_metrics(eval_pred):
    predictions, label_ids = eval_pred

    main_logits, adv_logits = predictions
    main_labels, skin_labels = label_ids

    main_preds = np.argmax(main_logits, axis=1)
    adv_preds = np.argmax(adv_logits, axis=1)
    # adv_preds = adv_logits.squeeze()

    # stable softmax for PR-AUC
    shifted = main_logits - np.max(main_logits, axis=1, keepdims=True)
    main_probs = np.exp(shifted) / np.exp(shifted).sum(axis=1, keepdims=True)

    metrics = {}

    # Main task metrics
    metrics["accuracy"] = accuracy.compute(
        predictions=main_preds, references=main_labels
    )["accuracy"]
    metrics["precision"] = precision.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["precision"]
    metrics["recall"] = recall.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["recall"]
    metrics["f1"] = f1.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["f1"]
    metrics["pr_auc"] = average_precision_score(main_labels, main_probs[:, 1])

    # Adversarial task metrics
    # metrics["adv_mae"] = mae.compute(
    #     predictions=adv_preds, references=skin_labels
    # )["mae"]

    metrics["adv_accuracy"] = accuracy.compute(
        predictions=adv_preds, references=skin_labels
    )["accuracy"]

    return metrics

Requirement already satisfied: evaluate in /usr/local/lib/python3.13/dist-packages (0.4.6)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.8.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.1.3)
Requirement already satisfied: dill in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.13/dist-packages (from evaluate) (0.70.19)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.12.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from evaluate) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from evaluate) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (4.0.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (23.0.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->evaluate) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->evaluate) (2026.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.25.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

Downloading builder script: 0.00B [00:00, ?B/s]

#### Prepare Data

In [ ]:
from torch.utils.data import Dataset
from PIL import Image
class AdversarialSkinLesionDataset(Dataset):
    def __init__(self, labels, skin_tones, img_paths, transform=None):
        self.labels = labels
        self.img_paths = img_paths
        self.transform = transform
        self.skin_tones = skin_tones

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = Image.open(self.img_paths[idx]).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        skin_tone = torch.tensor(self.skin_tones[idx], dtype=torch.long)

        if self.transform is not None:
            image = self.transform(image)

        return {
            "pixel_values": image,
            "labels": label,
            "skin_tone_labels": skin_tone
        }

from transformers import Trainer

class AdversarialTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(
            pixel_values=inputs["pixel_values"],
            labels=inputs.get("labels"),
            skin_tone_labels=inputs.get("skin_tone_labels"),
        )
        loss = outputs["loss"]
        return (loss, outputs) if return_outputs else loss

    def prediction_step(self, model, inputs, prediction_loss_only, ignore_keys=None):
        has_labels = "labels" in inputs and "skin_tone_labels" in inputs

        inputs = self._prepare_inputs(inputs)

        with torch.no_grad():
            outputs = model(
                pixel_values=inputs["pixel_values"],
                labels=inputs.get("labels"),
                skin_tone_labels=inputs.get("skin_tone_labels"),
            )

        loss = outputs["loss"].detach() if has_labels and outputs.get("loss") is not None else None

        if prediction_loss_only:
            return (loss, None, None)

        logits = (
            outputs["logits"].detach(),
            outputs["adversarial_logits"].detach(),
        )

        labels = None
        if has_labels:
            labels = (
                inputs["labels"].detach(),
                inputs["skin_tone_labels"].detach(),
            )

        return (loss, logits, labels)

#### Swin Model with Adversarial Network

In [ ]:
import torch
from transformers import AutoModelForImageClassification

class SwinModelWithAdversarial(torch.nn.Module):
    def __init__(
        self,
        model_name,
        prop=0.75,
        num_labels=2,
        adv_classes=5,
        lambda_=0.0,
        pred_loss_fn=torch.nn.CrossEntropyLoss(),
        adv_loss_fn=torch.nn.CrossEntropyLoss()
    ):
        super().__init__()

        self.model = AutoModelForImageClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            output_hidden_states=True,
            ignore_mismatched_sizes=True,
            output_attentions=True
        )

        self.pred_loss_fn = pred_loss_fn
        self.adv_loss_fn = adv_loss_fn
        self.lambda_ = lambda_

        for param in self.model.swin.parameters():
            param.requires_grad = False

        all_blocks = []
        for stage in self.model.swin.encoder.layers:
            all_blocks.extend(stage.blocks)

        n_blocks = len(all_blocks)
        n_unfreeze = max(1, int(n_blocks * prop))

        for block in all_blocks[-n_unfreeze:]:
            for param in block.parameters():
                param.requires_grad = True

        for param in self.model.classifier.parameters():
            param.requires_grad = True

        hidden_size = self.model.config.hidden_size

        self.adversarial = torch.nn.Sequential(
            torch.nn.Linear(hidden_size, 128),
            torch.nn.GELU(),
            torch.nn.Linear(128, adv_classes),
        )

    def forward(
        self,
        pixel_values,
        labels=None,
        skin_tone_labels=None,
        output_attentions=False,
        output_hidden_states=True,
        return_dict=True,
    ):
        outputs = self.model(
            pixel_values=pixel_values,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

        features = outputs.hidden_states[-1].mean(dim=1)
        logits = outputs.logits

        reverse_features = grad_reverse(features, lambda_=self.lambda_)
        adversarial_logits = self.adversarial(reverse_features)

        prediction_loss = None
        adversarial_loss = None
        total_loss = None

        if labels is not None:
            labels = labels.view(-1).long()
            prediction_loss = self.pred_loss_fn(logits, labels)

        if skin_tone_labels is not None:
            skin_tone_labels = skin_tone_labels.view(-1).long()
            # skin_tone_labels = skin_tone_labels.float().view(-1, 1)
            adversarial_loss = self.adv_loss_fn(adversarial_logits, skin_tone_labels)

        if prediction_loss is not None and adversarial_loss is not None:
            total_loss = prediction_loss + adversarial_loss
        elif prediction_loss is not None:
            total_loss = prediction_loss

        return {
            "loss": total_loss,
            "logits": logits,
            "adversarial_logits": adversarial_logits,
            "attentions": outputs.attentions,
            "hidden_states": outputs.hidden_states,
        }

Fine Tune Alpha

In [ ]:
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

NUM_CLASSES = 3

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# -------------------------
# 1) Split off TEST set
# -------------------------
# 5 folds -> one fold is 20% test
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
trainval_idx, test_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

trainval_imgs = img_paths[trainval_idx]
trainval_dx = dx[trainval_idx]
trainval_skin_tones = skin_tones[trainval_idx]
trainval_patient_ids = patient_ids[trainval_idx]

trainval_strata = np.array([f"{d}_{s}" for d, s in zip(trainval_dx, trainval_skin_tones)])

# 4 folds -> one fold is 25% of trainval = 20% of original
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

with open(f'/content/drive/MyDrive/Thesis/swin_adv_fine_tune_reg_{NUM_CLASSES}.csv', 'a', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Precision", "Recall", "F1", "PR-AUC", "Adversarial Accuracy", "Equal Opportuinity",
                   "Equalized Odds", "Demographic Parity"])

  # Get Preprocessed Data
  for lambda_ in [0.03, 0.04, 0.05, 0, 0.01, 0.02]:
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(trainval_imgs, trainval_strata, trainval_patient_ids)):
        train_imgs, val_imgs = trainval_imgs[train_idx], trainval_imgs[val_idx]
        train_dx, val_dx = trainval_dx[train_idx], trainval_dx[val_idx]
        train_skin_tones, val_skin_tones = trainval_skin_tones[train_idx], trainval_skin_tones[val_idx]

        image_processor = AutoImageProcessor.from_pretrained(model_name)
        train_transform, val_transform = preprocess(image_processor)
        train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
        val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

        model = SwinModelWithAdversarial(model_name, lambda_=lambda_, adv_classes=NUM_CLASSES)

        # Train the model
        training_args = TrainingArguments(
            output_dir="./trains",
            per_device_train_batch_size=64,
            per_device_eval_batch_size=64,
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            num_train_epochs=5,
            learning_rate=1e-5,
            save_total_limit=2,
            remove_unused_columns=False,
            load_best_model_at_end=True,
            metric_for_best_model="pr_auc",
            greater_is_better=True,
            dataloader_num_workers=8,
            dataloader_pin_memory=True,
            fp16=torch.cuda.is_available(),
            report_to="none",
            disable_tqdm=False,
        )

        trainer = AdversarialTrainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics
        )

        # Get the results on the validation dataset
        trainer.train()
        eval_results = trainer.evaluate()

        # Get the results for the light, medium, and dark datasets
        val_results = trainer.predict(val_ds)

        val_pred = np.argmax(val_results.predictions[0], axis=1)
        val_dx = np.array(val_dx)

        equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
        demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
        equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

        # Failsafe in case the runtime breaks
        print(eval_results)
        print("Equal Opportunity:", equal_opportunity)
        print("Demographic Parity:", demographic_parity)
        print("Equalized Odds:", equalized_odds)

        writer.writerow([
          model_name,
          lambda_,
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
          eval_results.get("eval_adv_accuracy"),
          equal_opportunity,
          equalized_odds,
          demographic_parity,
        ])

Getting ISIC...
Getting MILK...
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0819858312606812, 'eval_accuracy': 0.8888547743322075, 'eval_precision': 0.8757475083056478, 'eval_recall': 0.882786336235767, 'eval_f1': 0.8792528352234823, 'eval_pr_auc': 0.9361115698517839, 'eval_adv_accuracy': 0.6005526558182377, 'eval_runtime': 17.633, 'eval_samples_per_second': 184.71, 'eval_steps_per_second': 2.892, 'epoch': 5.0}
Equal Opportunity: 0.24057315233785825
Demographic Parity: 0.5577579875137716
Equalized Odds: 0.20918360886260362

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0603649616241455, 'eval_accuracy': 0.8989867976665643, 'eval_precision': 0.8760490639122014, 'eval_recall': 0.9082998661311914, 'eval_f1': 0.8918830101873152, 'eval_pr_auc': 0.9265330765242138, 'eval_adv_accuracy': 0.6005526558182377, 'eval_runtime': 18.6652, 'eval_samples_per_second': 174.496, 'eval_steps_per_second': 2.732, 'epoch': 5.0}
Equal Opportunity: 0.30090497737556554
Demographic Parity: 0.5752980083982105
Equalized Odds: 0.2490332456174203

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0801178216934204, 'eval_accuracy': 0.8863636363636364, 'eval_precision': 0.8515967438948028, 'eval_recall': 0.9109176155391828, 'eval_f1': 0.8802588996763754, 'eval_pr_auc': 0.9263835489558866, 'eval_adv_accuracy': 0.6044226044226044, 'eval_runtime': 14.5401, 'eval_samples_per_second': 223.933, 'eval_steps_per_second': 3.508, 'epoch': 5.0}
Equal Opportunity: 0.23634462932311173
Demographic Parity: 0.5855075792374828
Equalized Odds: 0.22493060786647828

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0842941999435425, 'eval_accuracy': 0.8931532084740559, 'eval_precision': 0.8701550387596899, 'eval_recall': 0.9016064257028112, 'eval_f1': 0.8856015779092702, 'eval_pr_auc': 0.9366060154011885, 'eval_adv_accuracy': 0.5756831439975437, 'eval_runtime': 18.0254, 'eval_samples_per_second': 180.689, 'eval_steps_per_second': 2.829, 'epoch': 5.0}
Equal Opportunity: 0.27786765895486165
Demographic Parity: 0.5458347586143988
Equalized Odds: 0.21813603274679827

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0963964462280273, 'eval_accuracy': 0.8774946269573227, 'eval_precision': 0.8632138114209827, 'eval_recall': 0.87073007367716, 'eval_f1': 0.8669556518839613, 'eval_pr_auc': 0.9290872261904533, 'eval_adv_accuracy': 0.5956401596561253, 'eval_runtime': 19.5608, 'eval_samples_per_second': 166.506, 'eval_steps_per_second': 2.607, 'epoch': 5.0}
Equal Opportunity: 0.039463367889188916
Demographic Parity: 0.509802486529014
Equalized Odds: 0.0935795693319223

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.4860823154449463, 'eval_accuracy': 0.8793368130181148, 'eval_precision': 0.8576072821846554, 'eval_recall': 0.883456128600134, 'eval_f1': 0.8703398218409766, 'eval_pr_auc': 0.9172483946164826, 'eval_adv_accuracy': 0.2542216763893153, 'eval_runtime': 17.6237, 'eval_samples_per_second': 184.808, 'eval_steps_per_second': 2.894, 'epoch': 5.0}
Equal Opportunity: 0.2462292609351433
Demographic Parity: 0.5624678663239074
Equalized Odds: 0.22055155299777776

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 16.600997924804688, 'eval_accuracy': 0.8891618053423396, 'eval_precision': 0.8486153846153847, 'eval_recall': 0.9230254350736279, 'eval_f1': 0.8842577749278615, 'eval_pr_auc': 0.9083880451009946, 'eval_adv_accuracy': 0.08627571384709856, 'eval_runtime': 18.4777, 'eval_samples_per_second': 176.266, 'eval_steps_per_second': 2.76, 'epoch': 5.0}
Equal Opportunity: 0.03099774892562357
Demographic Parity: 0.5883527431410039
Equalized Odds: 0.13527943594113445

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 14.122257232666016, 'eval_accuracy': 0.878992628992629, 'eval_precision': 0.8292390653085681, 'eval_recall': 0.926992632283992, 'eval_f1': 0.8753953194180898, 'eval_pr_auc': 0.9164857662783454, 'eval_adv_accuracy': 0.085995085995086, 'eval_runtime': 14.3167, 'eval_samples_per_second': 227.427, 'eval_steps_per_second': 3.562, 'epoch': 5.0}
Equal Opportunity: 0.1752765920376339
Demographic Parity: 0.6093017914561323
Equalized Odds: 0.21338234363786457

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.429970145225525, 'eval_accuracy': 0.8870125882714154, 'eval_precision': 0.8475308641975309, 'eval_recall': 0.9190093708165997, 'eval_f1': 0.8818240205523442, 'eval_pr_auc': 0.9215820887828539, 'eval_adv_accuracy': 0.3656739330672398, 'eval_runtime': 18.0546, 'eval_samples_per_second': 180.397, 'eval_steps_per_second': 2.825, 'epoch': 5.0}
Equal Opportunity: 0.22908914415143178
Demographic Parity: 0.5679938883947914
Equalized Odds: 0.21308090825197745

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.7362534999847412, 'eval_accuracy': 0.867055572612834, 'eval_precision': 0.8271604938271605, 'eval_recall': 0.8975217682518419, 'eval_f1': 0.8609058785737231, 'eval_pr_auc': 0.9121292727846965, 'eval_adv_accuracy': 0.13447958243782623, 'eval_runtime': 19.3604, 'eval_samples_per_second': 168.23, 'eval_steps_per_second': 2.634, 'epoch': 5.0}
Equal Opportunity: 0.06650086976976233
Demographic Parity: 0.5440654474928871
Equalized Odds: 0.13455391007948764

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 9.031495094299316, 'eval_accuracy': 0.8735032238256064, 'eval_precision': 0.8458093410108766, 'eval_recall': 0.8854655056932351, 'eval_f1': 0.8651832460732984, 'eval_pr_auc': 0.9069695355665526, 'eval_adv_accuracy': 0.08596868283696653, 'eval_runtime': 17.6703, 'eval_samples_per_second': 184.32, 'eval_steps_per_second': 2.886, 'epoch': 5.0}
Equal Opportunity: 0.2462292609351433
Demographic Parity: 0.5659658464928388
Equalized Odds: 0.22687040516551055

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 5.982270240783691, 'eval_accuracy': 0.880871968068775, 'eval_precision': 0.8460575719649562, 'eval_recall': 0.9049531459170014, 'eval_f1': 0.8745148771021992, 'eval_pr_auc': 0.9001961830037181, 'eval_adv_accuracy': 0.0868897758673626, 'eval_runtime': 18.5104, 'eval_samples_per_second': 175.955, 'eval_steps_per_second': 2.755, 'epoch': 5.0}
Equal Opportunity: 0.1222780569514238
Demographic Parity: 0.5825686814443459
Equalized Odds: 0.18501740445296846

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 6.896996021270752, 'eval_accuracy': 0.870085995085995, 'eval_precision': 0.8195937873357229, 'eval_recall': 0.9189551239115874, 'eval_f1': 0.8664351120934638, 'eval_pr_auc': 0.9020103299712867, 'eval_adv_accuracy': 0.08507371007371008, 'eval_runtime': 14.1614, 'eval_samples_per_second': 229.92, 'eval_steps_per_second': 3.601, 'epoch': 5.0}
Equal Opportunity: 0.1741440892063768
Demographic Parity: 0.6060174552135967
Equalized Odds: 0.21427910720350943

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 7.879636764526367, 'eval_accuracy': 0.8771875959471906, 'eval_precision': 0.8263723150357996, 'eval_recall': 0.9270414993306559, 'eval_f1': 0.8738170347003155, 'eval_pr_auc': 0.9064261231471831, 'eval_adv_accuracy': 0.08351243475591034, 'eval_runtime': 18.1382, 'eval_samples_per_second': 179.566, 'eval_steps_per_second': 2.812, 'epoch': 5.0}
Equal Opportunity: 0.23475165830771716
Demographic Parity: 0.5789081206813984
Equalized Odds: 0.22929391728463328

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 13.797239303588867, 'eval_accuracy': 0.8569235492784771, 'eval_precision': 0.8047477744807122, 'eval_recall': 0.9082384460817147, 'eval_f1': 0.8533668974197609, 'eval_pr_auc': 0.8963126421132522, 'eval_adv_accuracy': 0.08627571384709856, 'eval_runtime': 19.4198, 'eval_samples_per_second': 167.715, 'eval_steps_per_second': 2.626, 'epoch': 5.0}
Equal Opportunity: 0.05935301270413984
Demographic Parity: 0.5642856489401604
Equalized Odds: 0.15140257142048713

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0025453567504883, 'eval_accuracy': 0.8906969603929997, 'eval_precision': 0.873767258382643, 'eval_recall': 0.8901540522438044, 'eval_f1': 0.8818845388188454, 'eval_pr_auc': 0.9406045871152897, 'eval_adv_accuracy': 0.6367823150138164, 'eval_runtime': 17.6351, 'eval_samples_per_second': 184.688, 'eval_steps_per_second': 2.892, 'epoch': 5.0}
Equal Opportunity: 0.2473604826546003
Demographic Parity: 0.5573999265515975
Equalized Odds: 0.20996755476013598

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 0.9648191928863525, 'eval_accuracy': 0.8996008596868283, 'eval_precision': 0.8762088974854932, 'eval_recall': 0.9096385542168675, 'eval_f1': 0.8926108374384236, 'eval_pr_auc': 0.9263678582732451, 'eval_adv_accuracy': 0.6711697881486031, 'eval_runtime': 18.3795, 'eval_samples_per_second': 177.208, 'eval_steps_per_second': 2.775, 'epoch': 5.0}
Equal Opportunity: 0.30203619909502255
Demographic Parity: 0.5740126613545088
Equalized Odds: 0.24736671362000595

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 0.9932913184165955, 'eval_accuracy': 0.8915847665847666, 'eval_precision': 0.8589420654911839, 'eval_recall': 0.9135967849966511, 'eval_f1': 0.8854268094774423, 'eval_pr_auc': 0.9279861509216933, 'eval_adv_accuracy': 0.6750614250614251, 'eval_runtime': 13.263, 'eval_samples_per_second': 245.495, 'eval_steps_per_second': 3.845, 'epoch': 5.0}
Equal Opportunity: 0.24087464064814013
Demographic Parity: 0.5871497473587506
Equalized Odds: 0.2238599393716891

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 0.9956957101821899, 'eval_accuracy': 0.8922321154436598, 'eval_precision': 0.8670520231213873, 'eval_recall': 0.9036144578313253, 'eval_f1': 0.8849557522123894, 'eval_pr_auc': 0.9353957526328582, 'eval_adv_accuracy': 0.6352471599631563, 'eval_runtime': 18.2538, 'eval_samples_per_second': 178.429, 'eval_steps_per_second': 2.794, 'epoch': 5.0}
Equal Opportunity: 0.28013266461737574
Demographic Parity: 0.5503363663314406
Equalized Odds: 0.22298877367329342

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0125741958618164, 'eval_accuracy': 0.8784157199877187, 'eval_precision': 0.8540994189799871, 'eval_recall': 0.8861352980576022, 'eval_f1': 0.8698224852071006, 'eval_pr_auc': 0.9289152438182426, 'eval_adv_accuracy': 0.6567393306723979, 'eval_runtime': 19.5269, 'eval_samples_per_second': 166.796, 'eval_steps_per_second': 2.612, 'epoch': 5.0}
Equal Opportunity: 0.06545548254090972
Demographic Parity: 0.5248812998014802
Equalized Odds: 0.1154909312640234

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.01859712600708, 'eval_accuracy': 0.8910039914031317, 'eval_precision': 0.8743421052631579, 'eval_recall': 0.8901540522438044, 'eval_f1': 0.8821772319946897, 'eval_pr_auc': 0.9407054799732169, 'eval_adv_accuracy': 0.6251151366287995, 'eval_runtime': 17.6668, 'eval_samples_per_second': 184.357, 'eval_steps_per_second': 2.887, 'epoch': 5.0}
Equal Opportunity: 0.24849170437405732
Demographic Parity: 0.5580426000734484
Equalized Odds: 0.2105331656198645

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 0.9867779016494751, 'eval_accuracy': 0.8999078906969604, 'eval_precision': 0.8772609819121447, 'eval_recall': 0.9089692101740294, 'eval_f1': 0.8928336620644313, 'eval_pr_auc': 0.9263392299600931, 'eval_adv_accuracy': 0.6638010439054345, 'eval_runtime': 18.6355, 'eval_samples_per_second': 174.774, 'eval_steps_per_second': 2.737, 'epoch': 5.0}
Equal Opportunity: 0.30090497737556554
Demographic Parity: 0.5733699878326579
Equalized Odds: 0.24680110276027745

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0122958421707153, 'eval_accuracy': 0.89004914004914, 'eval_precision': 0.8580441640378549, 'eval_recall': 0.9109176155391828, 'eval_f1': 0.8836907082521117, 'eval_pr_auc': 0.9278570625560951, 'eval_adv_accuracy': 0.6627764127764127, 'eval_runtime': 14.5545, 'eval_samples_per_second': 223.71, 'eval_steps_per_second': 3.504, 'epoch': 5.0}
Equal Opportunity: 0.23860963498562593
Demographic Parity: 0.5858635737253101
Equalized Odds: 0.222727436540432

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.01531183719635, 'eval_accuracy': 0.8925391464537918, 'eval_precision': 0.8671373555840821, 'eval_recall': 0.9042838018741634, 'eval_f1': 0.8853211009174312, 'eval_pr_auc': 0.935648711321457, 'eval_adv_accuracy': 0.6232729505680074, 'eval_runtime': 18.0622, 'eval_samples_per_second': 180.321, 'eval_steps_per_second': 2.824, 'epoch': 5.0}
Equal Opportunity: 0.28013266461737574
Demographic Parity: 0.5496932795147204
Equalized Odds: 0.22224472605424578

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0353807210922241, 'eval_accuracy': 0.8765735339269266, 'eval_precision': 0.86006600660066, 'eval_recall': 0.8727394507702613, 'eval_f1': 0.8663563829787234, 'eval_pr_auc': 0.9290344921460311, 'eval_adv_accuracy': 0.645072152287381, 'eval_runtime': 19.6028, 'eval_samples_per_second': 166.15, 'eval_steps_per_second': 2.602, 'epoch': 5.0}
Equal Opportunity: 0.04286087638296021
Demographic Parity: 0.5149438747038213
Equalized Odds: 0.09899303383140826

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0383363962173462, 'eval_accuracy': 0.8919250844335278, 'eval_precision': 0.8765676567656766, 'eval_recall': 0.8894842598794374, 'eval_f1': 0.8829787234042553, 'eval_pr_auc': 0.9408201871960263, 'eval_adv_accuracy': 0.6189745164261591, 'eval_runtime': 17.9009, 'eval_samples_per_second': 181.946, 'eval_steps_per_second': 2.849, 'epoch': 5.0}
Equal Opportunity: 0.2473604826546003
Demographic Parity: 0.5561145795078958
Equalized Odds: 0.20847945952204075

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.014272689819336, 'eval_accuracy': 0.8992938286766964, 'eval_precision': 0.8771021992238034, 'eval_recall': 0.9076305220883534, 'eval_f1': 0.8921052631578947, 'eval_pr_auc': 0.9262942009017486, 'eval_adv_accuracy': 0.6416948111759287, 'eval_runtime': 18.6925, 'eval_samples_per_second': 174.241, 'eval_steps_per_second': 2.728, 'epoch': 5.0}
Equal Opportunity: 0.2986425339366515
Demographic Parity: 0.572084640788956
Equalized Odds: 0.24566988104082044

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0393271446228027, 'eval_accuracy': 0.8866707616707616, 'eval_precision': 0.8516896120150188, 'eval_recall': 0.9115874079035499, 'eval_f1': 0.8806211582012293, 'eval_pr_auc': 0.9270677806872382, 'eval_adv_accuracy': 0.6421990171990172, 'eval_runtime': 14.4445, 'eval_samples_per_second': 225.415, 'eval_steps_per_second': 3.531, 'epoch': 5.0}
Equal Opportunity: 0.23747713215436883
Demographic Parity: 0.5884359209921911
Equalized Odds: 0.22588142322004157

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0404335260391235, 'eval_accuracy': 0.893460239484188, 'eval_precision': 0.8692852543464262, 'eval_recall': 0.9036144578313253, 'eval_f1': 0.8861174926156875, 'eval_pr_auc': 0.9361827600621655, 'eval_adv_accuracy': 0.6017807798587658, 'eval_runtime': 18.0182, 'eval_samples_per_second': 180.761, 'eval_steps_per_second': 2.83, 'epoch': 5.0}
Equal Opportunity: 0.27900016178611875
Demographic Parity: 0.5471209322478393
Equalized Odds: 0.21944633178147444

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.0563693046569824, 'eval_accuracy': 0.8768805649370587, 'eval_precision': 0.8611111111111112, 'eval_recall': 0.8720696584058941, 'eval_f1': 0.8665557404326123, 'eval_pr_auc': 0.9290808578309302, 'eval_adv_accuracy': 0.6306416948111759, 'eval_runtime': 19.5979, 'eval_samples_per_second': 166.191, 'eval_steps_per_second': 2.602, 'epoch': 5.0}
Equal Opportunity: 0.04172837355170311
Demographic Parity: 0.5130158541382686
Equalized Odds: 0.0969408983147396

Evaluate

In [ ]:
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

NUM_CLASSES = 3

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# -------------------------
# 1) Split off TEST set
# -------------------------
# 5 folds -> one fold is 20% test
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

# Create the actual path

import sklearn
print("sklearn", sklearn.__version__)
print("pandas", pd.__version__)
print("numpy", np.__version__)

# -------------------------
# 3) Verify no patient leakage
# -------------------------
assert set(train_patient_ids).isdisjoint(set(val_patient_ids))

print("Train:", len(train_imgs))
print("Val:", len(val_imgs))
print("No patient overlap across splits.")

lambda_ = 0.04

image_processor = AutoImageProcessor.from_pretrained(model_name)
train_transform, val_transform = preprocess(image_processor)
train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

model = SwinModelWithAdversarial(model_name, lambda_=lambda_, adv_classes=NUM_CLASSES)

# Train the model
training_args = TrainingArguments(
    output_dir="./trains",
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    num_train_epochs=10,
    learning_rate=1e-5,
    save_total_limit=2,
    remove_unused_columns=False,
    load_best_model_at_end=True,
    metric_for_best_model="pr_auc",
    greater_is_better=True,
    dataloader_num_workers=0,
    dataloader_pin_memory=True,
    fp16=torch.cuda.is_available(),
    report_to="none",
    disable_tqdm=False,
)

trainer = AdversarialTrainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

# Get the results on the validation dataset
trainer.train()
eval_results = trainer.evaluate()

# Get the results for the light, medium, and dark datasets
val_results = trainer.predict(val_ds)
val_pred = np.argmax(val_results.predictions[0], axis=1)
val_dx = np.array(val_dx)

equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

print("Equal Opportunity:", equal_opportunity)
print("Demographic Parity:", demographic_parity)
print("Equalized Odds:", equalized_odds)

# Failsafe in case the runtime breaks
print(eval_results)

# Save the model
trainer.save_model(f'./swin_adversarial_{lambda_}')
trainer.save_state()

Getting ISIC...
----- ISIC -----
Number images: 10121
Number malignant images: 2066
Number benign images: 8055
Number images with skin tone 0: 6012
Number images with skin tone 1: 2538
Number images with skin tone 2: 1571
Getting MILK...
Number images: 10234
Number malignant images: 7268
Number benign images: 2966
Number skin tones: [0 1 2]
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...
---- Combined Datasets -----
Number images: 20355
Number malignant images: 9334
Number benign images: 11021
Number images with skin tone 0: 8878
Number images with skin tone 1: 9722
Number images with skin tone 2: 1755

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `1000`.

sklearn 1.6.1
pandas 2.2.3
numpy 2.1.3
Train: 16320
Val: 4035
No patient overlap across splits.

Loading weights:   0%|          | 0/221 [00:00<?, ?it/s]

[transformers] SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Equal Opportunity: 0.17104830759119294
Demographic Parity: 0.5156184644213556
Equalized Odds: 0.19211682574404101
{'eval_loss': 1.1867858171463013, 'eval_accuracy': 0.8721189591078067, 'eval_precision': 0.8189442525900346, 'eval_recall': 0.9176340519624102, 'eval_f1': 0.8654848800834203, 'eval_pr_auc': 0.8987970758214882, 'eval_adv_accuracy': 0.5283767038413879}

NameError: name 'writer' is not defined

### Oversampling + Swin Transformer

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
!pip install fairlearn
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# Create test dataset
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

# Ensures no patient id leakage
assert set(train_patient_ids).isdisjoint(set(val_patient_ids))

# Oversample such that the same number of images in each strata
# NOTE: Most benign classes is in the light dataset and the most malignant classes is in the medium dataset

# Make each dataset have the same number of benign cases
light_benign_idx = np.where((train_skin_tones == 0) & (train_dx == 0))[0]
medium_benign_idx = np.where((train_skin_tones == 1) & (train_dx == 0))[0]
dark_benign_idx = np.where((train_skin_tones == 2) & (train_dx == 0))[0]

light_medium_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[medium_benign_idx]])
light_medium_dx = np.concatenate([train_dx[light_benign_idx], train_dx[medium_benign_idx] + 1]) # Add one so that we oversample medium_dx, will change back to 0
light_medium_paths, light_medium_dx, _, _ = oversample_minority(light_medium_paths, light_medium_dx)
medium_benign_paths = light_medium_paths[light_medium_dx == 1]

light_dark_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[dark_benign_idx]])
light_dark_dx = np.concatenate([train_dx[light_benign_idx], train_dx[dark_benign_idx] + 1])
light_dark_paths, light_dark_dx, _, _ = oversample_minority(light_dark_paths, light_dark_dx)
dark_benign_paths = light_dark_paths[light_dark_dx == 1]

light_benign_paths = train_imgs[light_benign_idx]
print(f"Oversampled light benign: {len(light_benign_paths)}")
print(f"Oversampled medium benign: {len(medium_benign_paths)}")
print(f"Oversampled dark benign: {len(dark_benign_paths)}")

# Make each dataset have the same number of malignant classes
light_malignant_idx = np.where((train_skin_tones == 0) & (train_dx == 1))[0]
medium_malignant_idx = np.where((train_skin_tones == 1) & (train_dx == 1))[0]
dark_malignant_idx = np.where((train_skin_tones == 2) & (train_dx == 1))[0]

medium_light_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[light_malignant_idx]])
medium_light_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[light_malignant_idx]])
medium_light_paths, medium_light_dx, _, _ = oversample_minority(medium_light_paths, medium_light_dx)
light_malignant_paths = medium_light_paths[medium_light_dx == 1]

medium_dark_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[dark_malignant_idx]])
medium_dark_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[dark_malignant_idx]])
medium_dark_paths, medium_dark_dx, _, _ = oversample_minority(medium_dark_paths, medium_dark_dx)
dark_malignant_paths = medium_dark_paths[medium_dark_dx == 1]

medium_malignant_paths = train_imgs[medium_malignant_idx]
print(f"Oversampled medium malignant: {len(light_malignant_paths)}")
print(f"Oversampled medium malignant: {len(medium_malignant_paths)}")
print(f"Oversampled dark malignant: {len(dark_malignant_paths)}")

# Combine the datasets
benign_paths = np.concatenate([light_benign_paths, medium_benign_paths, dark_benign_paths])
benign_dx = np.zeros(len(benign_paths))
malignant_paths = np.concatenate([light_malignant_paths, medium_malignant_paths, dark_malignant_paths])
malignant_dx = np.ones(len(malignant_paths))
benign_skin_tones = np.concatenate([np.zeros(len(light_benign_paths)), np.ones(len(medium_benign_paths)), np.ones(len(dark_benign_paths)) * 2])
malignant_skin_tones = np.concatenate([np.zeros(len(light_malignant_paths)), np.ones(len(medium_malignant_paths)), np.ones(len(dark_malignant_paths)) * 2])

train_imgs = np.concatenate([benign_paths, malignant_paths])
train_dx = np.concatenate([benign_dx, malignant_dx])
train_skin_tones = np.concatenate([benign_skin_tones, malignant_skin_tones])

# Shuffle the order
indices = np.arange(len(train_imgs))
np.random.shuffle(indices)
train_imgs = train_imgs[indices]
train_dx = train_dx[indices]
train_skin_tones = train_skin_tones[indices]

assert(len(train_imgs) == len(train_dx) == len(train_skin_tones))

with open('/content/drive/MyDrive/Thesis/swin_oversample_adversarial_2.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Fold", "Precision", "Recall", "F1", "PR-AUC",
                   "Light Precision", "Light Recall", "Light F1", "Light PR-AUC",
                   "Medium Precision", "Medium Recall", "Medium F1", "Medium PR-AUC",
                   "Dark Precision", "Dark Recall", "Dark F1", "Dark PR-AUC",])

  image_processor = AutoImageProcessor.from_pretrained(model_name)
  train_transform, val_transform = preprocess(image_processor)
  train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
  val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

  for lambda_ in [0]:
    model = SwinModelWithAdversarial(model_name, lambda_=lambda_)

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = AdversarialTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    # Get the results on the validation dataset
    trainer.train()
    eval_results = trainer.evaluate()

    val_results = trainer.predict(val_ds)
    val_pred = np.argmax(val_results.predictions[0], axis=1)
    val_dx = np.array(val_dx)

    equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
    demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
    equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones)

    # Failsafe in case the runtime breaks
    print(eval_results)

    writer.writerow([
      model_name,
      eval_results.get("eval_precision"),
      eval_results.get("eval_recall"),
      eval_results.get("eval_f1"),
      eval_results.get("eval_pr_auc"),
      equal_opportunity,
      equal_opportunity,
      demographic_parity,
      equalized_odds
    ])

    trainer.save_model(f'/content/drive/MyDrive/Thesis/models/swin_oversample_{lambda_}')
    trainer.save_state()

Requirement already satisfied: fairlearn in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: narwhals>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.20.0)
Requirement already satisfied: numpy>=1.24.4 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.4.4)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (3.0.2)
Requirement already satisfied: scikit-learn>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.8.0)
Requirement already satisfied: scipy<1.16.0,>=1.9.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.15.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2.9.0.post0)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->fairlearn) (1.17.0)
Getting ISIC...
Getting MILK...
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...
Oversampled light benign: 4117
Oversampled medium benign: 4117
Oversampled dark benign: 4117
Oversampled medium malignant: 4417
Oversampled medium malignant: 4417
Oversampled dark malignant: 4417

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 24.7101993560791, 'eval_accuracy': 0.855072463768116, 'eval_precision': 0.7856823266219239, 'eval_recall': 0.9405463310123192, 'eval_f1': 0.856167723061921, 'eval_pr_auc': 0.9030451912464973, 'eval_adv_accuracy': 0.0, 'eval_runtime': 18.9027, 'eval_samples_per_second': 215.366, 'eval_steps_per_second': 3.386, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.1510236263275146, 'eval_accuracy': 0.8811102923114714, 'eval_precision': 0.8603439291297551, 'eval_recall': 0.8843063738618104, 'eval_f1': 0.8721605916534602, 'eval_pr_auc': 0.9239920728485008, 'eval_adv_accuracy': 0.6182756079587325, 'eval_runtime': 18.9866, 'eval_samples_per_second': 214.414, 'eval_steps_per_second': 3.371, 'epoch': 10.0}

### Oversampling + Adversarial Network

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
!pip install fairlearn
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# Create test dataset
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

# Ensures no patient id leakage
assert set(train_patient_ids).isdisjoint(set(val_patient_ids))

# Oversample such that the same number of images in each strata
# NOTE: Most benign classes is in the light dataset and the most malignant classes is in the medium dataset

# Make each dataset have the same number of benign cases
light_benign_idx = np.where((train_skin_tones == 0) & (train_dx == 0))[0]
medium_benign_idx = np.where((train_skin_tones == 1) & (train_dx == 0))[0]
dark_benign_idx = np.where((train_skin_tones == 2) & (train_dx == 0))[0]

light_medium_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[medium_benign_idx]])
light_medium_dx = np.concatenate([train_dx[light_benign_idx], train_dx[medium_benign_idx] + 1]) # Add one so that we oversample medium_dx, will change back to 0
light_medium_paths, light_medium_dx, _, _ = oversample_minority(light_medium_paths, light_medium_dx)
medium_benign_paths = light_medium_paths[light_medium_dx == 1]

light_dark_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[dark_benign_idx]])
light_dark_dx = np.concatenate([train_dx[light_benign_idx], train_dx[dark_benign_idx] + 1])
light_dark_paths, light_dark_dx, _, _ = oversample_minority(light_dark_paths, light_dark_dx)
dark_benign_paths = light_dark_paths[light_dark_dx == 1]

light_benign_paths = train_imgs[light_benign_idx]
print(f"Oversampled light benign: {len(light_benign_paths)}")
print(f"Oversampled medium benign: {len(medium_benign_paths)}")
print(f"Oversampled dark benign: {len(dark_benign_paths)}")

# Make each dataset have the same number of malignant classes
light_malignant_idx = np.where((train_skin_tones == 0) & (train_dx == 1))[0]
medium_malignant_idx = np.where((train_skin_tones == 1) & (train_dx == 1))[0]
dark_malignant_idx = np.where((train_skin_tones == 2) & (train_dx == 1))[0]

medium_light_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[light_malignant_idx]])
medium_light_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[light_malignant_idx]])
medium_light_paths, medium_light_dx, _, _ = oversample_minority(medium_light_paths, medium_light_dx)
light_malignant_paths = medium_light_paths[medium_light_dx == 1]

medium_dark_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[dark_malignant_idx]])
medium_dark_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[dark_malignant_idx]])
medium_dark_paths, medium_dark_dx, _, _ = oversample_minority(medium_dark_paths, medium_dark_dx)
dark_malignant_paths = medium_dark_paths[medium_dark_dx == 1]

medium_malignant_paths = train_imgs[medium_malignant_idx]
print(f"Oversampled medium malignant: {len(light_malignant_paths)}")
print(f"Oversampled medium malignant: {len(medium_malignant_paths)}")
print(f"Oversampled dark malignant: {len(dark_malignant_paths)}")

# Combine the datasets
benign_paths = np.concatenate([light_benign_paths, medium_benign_paths, dark_benign_paths])
benign_dx = np.zeros(len(benign_paths))
malignant_paths = np.concatenate([light_malignant_paths, medium_malignant_paths, dark_malignant_paths])
malignant_dx = np.ones(len(malignant_paths))
benign_skin_tones = np.concatenate([np.zeros(len(light_benign_paths)), np.ones(len(medium_benign_paths)), np.ones(len(dark_benign_paths)) * 2])
malignant_skin_tones = np.concatenate([np.zeros(len(light_malignant_paths)), np.ones(len(medium_malignant_paths)), np.ones(len(dark_malignant_paths)) * 2])

train_imgs = np.concatenate([benign_paths, malignant_paths])
train_dx = np.concatenate([benign_dx, malignant_dx])
train_skin_tones = np.concatenate([benign_skin_tones, malignant_skin_tones])

# Shuffle the order
indices = np.arange(len(train_imgs))
np.random.shuffle(indices)
train_imgs = train_imgs[indices]
train_dx = train_dx[indices]
train_skin_tones = train_skin_tones[indices]

assert(len(train_imgs) == len(train_dx) == len(train_skin_tones))

with open('/content/drive/MyDrive/Thesis/swin_oversample_adversarial_2.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Fold", "Precision", "Recall", "F1", "PR-AUC",
                   "Light Precision", "Light Recall", "Light F1", "Light PR-AUC",
                   "Medium Precision", "Medium Recall", "Medium F1", "Medium PR-AUC",
                   "Dark Precision", "Dark Recall", "Dark F1", "Dark PR-AUC",])

  image_processor = AutoImageProcessor.from_pretrained(model_name)
  train_transform, val_transform = preprocess(image_processor)
  train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
  val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

  for lambda_ in [0.04]:
    model = SwinModelWithAdversarial(model_name, lambda_=lambda_)

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = AdversarialTrainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    # Get the results on the validation dataset
    trainer.train()
    eval_results = trainer.evaluate()

    val_results = trainer.predict(val_ds)
    val_pred = np.argmax(val_results.predictions[0], axis=1)
    val_dx = np.array(val_dx)

    equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
    demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
    equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones)

    # Failsafe in case the runtime breaks
    print(eval_results)

    writer.writerow([
      model_name,
      eval_results.get("eval_precision"),
      eval_results.get("eval_recall"),
      eval_results.get("eval_f1"),
      eval_results.get("eval_pr_auc"),
      equal_opportunity,
      equal_opportunity,
      demographic_parity,
      equalized_odds
    ])

    trainer.save_model(f'/content/drive/MyDrive/Thesis/models/swin_oversample_{lambda_}')
    trainer.save_state()

Requirement already satisfied: fairlearn in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: narwhals>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.20.0)
Requirement already satisfied: numpy>=1.24.4 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.4.4)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (3.0.2)
Requirement already satisfied: scikit-learn>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.8.0)
Requirement already satisfied: scipy<1.16.0,>=1.9.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.15.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2.9.0.post0)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->fairlearn) (1.17.0)
Getting ISIC...
Getting MILK...
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...
Light benign: 4117
Medium benign: 3361
Dark benign: 1339
Light malignant: 2985
Medium malignant: 4417
Dark malignant: 65
Oversampled light benign: 4417
Oversampled medium benign: 4417
Oversampled dark benign: 4417
Oversampled medium malignant: 4417
Oversampled medium malignant: 4417
Oversampled dark malignant: 4417
Train images: 26502

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 3.9157488346099854, 'eval_accuracy': 0.8798820928518791, 'eval_precision': 0.8551546391752577, 'eval_recall': 0.8885913229780397, 'eval_f1': 0.8715524034672971, 'eval_pr_auc': 0.9207419950901632, 'eval_adv_accuracy': 0.2891181527880128, 'eval_runtime': 19.2914, 'eval_samples_per_second': 211.027, 'eval_steps_per_second': 3.318, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

{'eval_loss': 1.1435106992721558, 'eval_accuracy': 0.8813559322033898, 'eval_precision': 0.8661375661375661, 'eval_recall': 0.8768077129084092, 'eval_f1': 0.8714399787064147, 'eval_pr_auc': 0.9186287104326263, 'eval_adv_accuracy': 0.6236796855809383, 'eval_runtime': 19.1991, 'eval_samples_per_second': 212.041, 'eval_steps_per_second': 3.333, 'epoch': 10.0}