## Imports

Important imports and packages used

In [ ]:
!pip install fairlearn
# from google.colab import userdata
import os
import kagglehub
import pandas as pd
import os
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve, auc
import torch
import transformers
import torchvision.transforms as T
from transformers import ViTForImageClassification, ViTImageProcessor, AutoConfig
from torch.utils.data import Dataset, DataLoader
from transformers import Trainer, TrainingArguments
from transformers import AutoModelForImageClassification, AutoImageProcessor

# import selectkbest

IMG_SIZE   = (128, 128)
# AUTOTUNE   = tf.data.AUTOTUNE

label_map = {'Benign': 0,
             'Malignant': 1}

Collecting fairlearn
  Downloading fairlearn-0.13.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: narwhals>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.19.0)
Requirement already satisfied: numpy>=1.24.4 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.0.2)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.2.2)
Requirement already satisfied: scikit-learn>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.6.1)
Collecting scipy<1.16.0,>=1.9.3 (from fairlearn)
  Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->fairlearn) (1.17.0)
Downloading fairlearn-0.13.0-py3-none-any.whl (251 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.6/251.6 kB 20.0 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 66.5 MB/s eta 0:00:00
Installing collected packages: scipy, fairlearn
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.3
    Uninstalling scipy-1.16.3:
      Successfully uninstalled scipy-1.16.3
Successfully installed fairlearn-0.13.0 scipy-1.15.3

## Load Dataset

In [ ]:
# os.environ["KAGGLE_USERNAME"] =  userdata.get('KAGGLE_USERNAME')
# os.environ["KAGGLE_KEY"] = userdata.get('KAGGLE_KEY')

os.environ["KAGGLE_USERNAME"] = "josephgalicinao"
os.environ["KAGGLE_KEY"] = "d222ce164adf121a586cdc25319e3bbc"

ISIC 2018

In [ ]:
isic2018_path = kagglehub.dataset_download("josephgalicinao/isic-2018-dataset")

print("Path to dataset files:", isic2018_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-dataset/1.archive...

100%|██████████| 237M/237M [00:02<00:00, 113MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-dataset/versions/1

ISIC 2018 Test

In [ ]:
# Download latest version
isic2018_test_path = kagglehub.dataset_download("josephgalicinao/isic-2018-test-dataset")

print("Path to dataset files:", isic2018_test_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-test-dataset/1.archive...

100%|██████████| 37.3M/37.3M [00:03<00:00, 11.8MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/isic-2018-test-dataset/versions/1

DDI + Milk10K + ISIC Archive

In [ ]:
# Download latest version
skin_tone_path = kagglehub.dataset_download("josephgalicinao/skin-tone-dataset")

print("Path to dataset files:", skin_tone_path)

Downloading to /root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/2.archive...

100%|██████████| 8.28G/8.28G [03:57<00:00, 37.5MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2

## Create Datasets

Create Fitzpatrick dataset + Unlabeled Fitzpatrick

In [ ]:
def get_fitzpatrick_datasets():
  # ISIC
  print("Getting ISIC...")
  df = pd.read_csv(f"{skin_tone_path}/Representative/ISIC_archive/isic_metadata.csv")
  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0}).values
  isic_skin_tone = df["fitzpatrick_skin_type"].map({'I': 0, 'II': 0, 'III': 1,
                                                         'IV': 1, 'V': 2, 'VI':2}).values
  isic_patient_ids = df["patient_id"].values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{skin_tone_path}/Representative/ISIC_archive/{isic_id}.jpg")

  # Dataset characteristics
  # print("----- ISIC -----")
  # print(f"Number images: {len(isic_paths)}")
  # print(f"Number malignant images: {np.sum(isic_dx == 1)}")
  # print(f"Number benign images: {np.sum(isic_dx == 0)}")

  assert len(isic_paths) == len(isic_ids) == len(isic_dx) == len(isic_skin_tone) == len(isic_patient_ids)

  # MILK
  print("Getting MILK...")
  df = pd.read_csv(f"{skin_tone_path}/Representative/Milk10K/metadata.csv")
  # Remove rows where dx is NaN or Indeterminate
  df = df.dropna(subset=['diagnosis_1'])
  df = df[df['diagnosis_1'] != 'Indeterminate']

  milk_ids = df["isic_id"].values
  milk_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0}).values
  milk_skin_tone = df["skin_tone_class"].map({5: 0, 4: 0, 3: 1, 2: 1, 1: 2, 0: 2}).values
  milk_patient_ids = df["lesion_id"].values

  milk_paths = []
  for milk_id in milk_ids:
    milk_paths.append(f"{skin_tone_path}/Representative/Milk10K/images/{milk_id}.jpg")

  # print("----- MILK -----")
  # print(f"Number images: {len(milk_paths)}")
  # print(f"Number malignant images: {np.sum(milk_dx == 1)}")
  # print(f"Number benign images: {np.sum(milk_dx == 0)}")
  # print(f"Number skin tones: {np.unique(milk_skin_tone)}")
  # unique, counts = np.unique(milk_skin_tone, return_counts=True)
  # for i in range(len(unique)):
  #   print(f"Number images with skin tone {unique[i]}: {counts[i]}")

  assert len(milk_paths) == len(milk_ids) == len(milk_dx) == len(milk_skin_tone) == len(milk_patient_ids)

  print("Combining Datasets...")
  paths = np.concatenate((isic_paths, milk_paths))
  dx = np.concatenate((isic_dx, milk_dx))
  skin_tone = np.concatenate((isic_skin_tone, milk_skin_tone))
  patient_ids = np.concatenate((isic_patient_ids, milk_patient_ids))

  # print("---- Combined Datasets -----")
  # print(f"Number images: {len(paths)}")
  # print(f"Number malignant images: {np.sum(dx == 1)}")
  # print(f"Number benign images: {np.sum(dx == 0)}")
  strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tone)])
  unique, counts = np.unique(strata, return_counts=True)
  for i in range(len(unique)):
    print(f"Number images with skin tone {unique[i]}: {counts[i]}")

  assert len(paths) == len(dx) == len(skin_tone)== len(patient_ids)

  return paths, dx, skin_tone, patient_ids

def get_train_isic2018():
  print("ISIC 2018 Training Dataset...")
  df = pd.read_csv(f"{isic2018_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values
  isic_patient_ids = df["lesion_id"].values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx) == len(isic_patient_ids)

  return isic_paths, isic_dx, isic_patient_ids

def get_test_isic2018():
  print("ISIC 2018 Test Dataset...")
  df = pd.read_csv(f"{isic2018_test_path}/metadata.csv")
  df = df.dropna(subset=['diagnosis_1'])

  isic_ids = df["isic_id"].values
  isic_dx = df["diagnosis_1"].map({'Malignant': 1, 'Benign': 0, 'Indeterminate': 1}).values

  isic_paths = []
  for isic_id in isic_ids:
    isic_paths.append(f"{isic2018_test_path}/{isic_id}.jpg")

  assert len(isic_paths) == len(isic_dx)

  return isic_paths, isic_dx

get_fitzpatrick_datasets()

Getting ISIC...
Getting MILK...
Combining Datasets...
Number images with skin tone 0_0: 5146
Number images with skin tone 0_1: 4201
Number images with skin tone 0_2: 1674
Number images with skin tone 1_0: 3732
Number images with skin tone 1_1: 5521
Number images with skin tone 1_2: 81

(array(['/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/ISIC_archive/ISIC_0076337.jpg',
        '/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/ISIC_archive/ISIC_0077599.jpg',
        '/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/ISIC_archive/ISIC_0079358.jpg',
        ...,
        '/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/Milk10K/images/ISIC_0075884.jpg',
        '/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/Milk10K/images/ISIC_0073863.jpg',
        '/root/.cache/kagglehub/datasets/josephgalicinao/skin-tone-dataset/versions/2/Representative/Milk10K/images/ISIC_0051817.jpg'],
       dtype='<U123'),
 array([1, 0, 0, ..., 0, 0, 1]),
 array([0, 1, 0, ..., 1, 1, 0]),
 array(['IP_7309176', 'IP_5007819', 'IP_9328831', ..., 'IL_9270970',
        'IL_2547802', 'IL_1612768'], dtype=object))

In [ ]:
def oversample_minority(x_train, y_train, abcde=None, weights=None):
    x_train = np.array(x_train)
    y_train = np.array(y_train)

    # Oversample the minority class
    pos_features = x_train[y_train == 1] # Get the malignant images
    neg_features = x_train[y_train == 0] # Get the benign images

    pos_labels = y_train[y_train == 1] # Get the malignant labels
    neg_labels = y_train[y_train == 0] # Get the benign labels

    if abcde is not None:
      pos_abcde = abcde[y_train == 1] # Get the malignant abcde features
      neg_abcde = abcde[y_train == 0] # Get the benign abcde features

    if weights is not None:
      pos_weights = weights[y_train == 1] # Get the malignant weights
      neg_weights = weights[y_train == 0] # Get the benign weights

    ids = np.arange(len(pos_features)) # Create an array that goes from 0 - len(pos_features)
    choice = np.random.choice(ids, len(neg_features)) # Choose len(neg_features) number of ids
    oversampled_pos_features = pos_features[choice] # Oversample the minority class to get images
    oversampled_pos_labels = pos_labels[choice] # Oversample the minority class to get labels
    if abcde is not None:
      oversampled_pos_abcde = pos_abcde[choice] # Oversample the minority class to get abcde features
    if weights is not None:
      oversampled_pos_weights = pos_weights[choice] # Oversample the minority class to get weights

    x_train = np.concatenate([oversampled_pos_features, neg_features], axis=0) # Concatenate the data sets
    y_train = np.concatenate([oversampled_pos_labels, neg_labels], axis=0) # Concatenate the data set

    if abcde is not None:
      abcde = np.concatenate([oversampled_pos_abcde, neg_abcde], axis=0) # Concatenate the
    if weights is not None:
      weights = np.concatenate([oversampled_pos_weights, neg_weights], axis=0) # Concatenate the data sets

    order = np.arange(len(x_train)) # Create an array that goes from 0 - len(x_train)
    np.random.shuffle(order) # Shuffle the array
    x_train = x_train[order] # Shuffle the images
    y_train = y_train[order] # Shuffle the labels

    if abcde is not None:
      abcde = abcde[order] # Shuffle the abcde features
    if weights is not None:
      weights = weights[order] # Shuffle the weights

    return x_train, y_train, abcde, weights

batch = 64

In [ ]:
def preprocess(image_processor):
  train_transform = T.Compose([
      T.Resize((224, 224)),
      T.RandomHorizontalFlip(p=0.5),
      T.RandomVerticalFlip(p=0.5),
      T.RandomApply([
          T.ColorJitter(
              brightness=0.1,
              contrast=0.1,
              saturation=0.1,
              hue=0.05
          )
      ], p=0.5),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
  ])

  val_transform = T.Compose([
      T.Resize((224, 224)),
      T.ToTensor(),
      T.Normalize(mean=image_processor.image_mean, std=image_processor.image_std),
      T.RandomErasing(p=0.5, scale=(0.02, 0.33), ratio=(0.3, 3.3), value=0, inplace=False),
  ])

  return train_transform, val_transform

# Pretrained Models

### Init

In [ ]:
# Stratifier
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

from PIL import Image

# Dataset class
class SkinLesionDataset(Dataset):
    def __init__(self, labels, img_paths, transform=None):
        self.labels = labels
        self.img_paths = img_paths
        self.transform = transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = Image.open(self.img_paths[idx]).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.long)

        if self.transform is not None:
            image = self.transform(image)

        return {
            "pixel_values": image,
            "labels": label,
        }

### Metrics

In [ ]:
!pip install evaluate
import evaluate
import numpy as np
from sklearn.metrics import average_precision_score

accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    probs = np.exp(logits) / np.exp(logits).sum(-1, keepdims=True)

    metrics = {}
    metrics.update(accuracy.compute(predictions=preds, references=labels))
    metrics.update(precision.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(recall.compute(predictions=preds, references=labels, average="binary"))
    metrics.update(f1.compute(predictions=preds, references=labels, average="binary"))

    metrics["pr_auc"] = average_precision_score(labels, probs[:, 1])

    return metrics

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.10.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

## ISIC 2018

Fine tune

In [ ]:
model_name = "google/vit-base-patch16-224"

img_paths, dx, patient_ids = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('/content/drive/MyDrive/Thesis/isic2018_fine_tuning_vit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for prop in [0.75, 0.5, 0.25, 0]:
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, patient_ids)):
      train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
      train_dx, val_dx = dx[train_idx], dx[val_idx]
      train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

      # Get Preprocessed Data
      image_processor = AutoImageProcessor.from_pretrained(model_name)
      train_transform, val_transform = preprocess(image_processor)
      train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
      val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

      print(f"Prop: {prop}")
      model = AutoModelForImageClassification.from_pretrained(
          model_name,
          num_labels=2,
          ignore_mismatched_sizes=True
      )

      # Freeze the whole ViT backbone first
      for param in model.vit.parameters():
          param.requires_grad = False

      layers = model.vit.encoder.layer
      n_layers = len(layers)
      print(f"Number of layers: {n_layers}")
      n_unfreeze = max(1, int(n_layers * prop))

      for layer in layers[-n_unfreeze:]:
          for param in layer.parameters():
              param.requires_grad = True

      # Keep classifier trainable
      for param in model.classifier.parameters():
          param.requires_grad = True

      # Train the model
      training_args = TrainingArguments(
          output_dir="./trains",
          per_device_train_batch_size=64,
          per_device_eval_batch_size=64,
          eval_strategy="epoch",
          save_strategy="epoch",
          logging_strategy="epoch",
          num_train_epochs=10,
          learning_rate=1e-5,
          save_total_limit=2,
          remove_unused_columns=False,
          load_best_model_at_end=True,
          metric_for_best_model="pr_auc",
          greater_is_better=True,
          dataloader_num_workers=8,
          dataloader_pin_memory=True,
          fp16=torch.cuda.is_available(),
          report_to="none",
          disable_tqdm=False,
      )

      trainer = Trainer(
          model=model,
          args=training_args,
          train_dataset=train_ds,
          eval_dataset=val_ds,
          compute_metrics=compute_metrics
      )

      trainer.train()

      eval_results = trainer.evaluate()

      print(eval_results)

      writer.writerow([
          prop,
          eval_results.get("eval_accuracy"),
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
      ])

ISIC 2018 Training Dataset...

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.75

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3427239656448364, 'eval_accuracy': 0.8789552988448016, 'eval_precision': 0.6907730673316709, 'eval_recall': 0.7030456852791879, 'eval_f1': 0.6968553459119496, 'eval_pr_auc': 0.7700256749254355, 'eval_runtime': 3.9622, 'eval_samples_per_second': 502.493, 'eval_steps_per_second': 8.076, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.75

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4415508210659027, 'eval_accuracy': 0.8739369684842421, 'eval_precision': 0.6779661016949152, 'eval_recall': 0.7017543859649122, 'eval_f1': 0.6896551724137931, 'eval_pr_auc': 0.7626655207699273, 'eval_runtime': 3.8603, 'eval_samples_per_second': 517.84, 'eval_steps_per_second': 8.29, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.75

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.48507004976272583, 'eval_accuracy': 0.8739537173806007, 'eval_precision': 0.6805970149253732, 'eval_recall': 0.6047745358090185, 'eval_f1': 0.6404494382022472, 'eval_pr_auc': 0.7112586290543538, 'eval_runtime': 4.0147, 'eval_samples_per_second': 505.895, 'eval_steps_per_second': 7.971, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.75

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.27688366174697876, 'eval_accuracy': 0.8752515090543259, 'eval_precision': 0.650103519668737, 'eval_recall': 0.7989821882951654, 'eval_f1': 0.7168949771689498, 'eval_pr_auc': 0.8097401299799996, 'eval_runtime': 4.0038, 'eval_samples_per_second': 496.525, 'eval_steps_per_second': 7.992, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.75

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.358987420797348, 'eval_accuracy': 0.8838484546360917, 'eval_precision': 0.7323529411764705, 'eval_recall': 0.6368286445012787, 'eval_f1': 0.6812585499316005, 'eval_pr_auc': 0.7610441973994841, 'eval_runtime': 3.9206, 'eval_samples_per_second': 511.657, 'eval_steps_per_second': 8.162, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.5

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.31070396304130554, 'eval_accuracy': 0.8663987945755901, 'eval_precision': 0.6553398058252428, 'eval_recall': 0.6852791878172588, 'eval_f1': 0.6699751861042184, 'eval_pr_auc': 0.7350203422414832, 'eval_runtime': 3.829, 'eval_samples_per_second': 519.974, 'eval_steps_per_second': 8.357, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.5

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3516344428062439, 'eval_accuracy': 0.8659329664832416, 'eval_precision': 0.6526806526806527, 'eval_recall': 0.7017543859649122, 'eval_f1': 0.6763285024154589, 'eval_pr_auc': 0.7538743801463996, 'eval_runtime': 3.8561, 'eval_samples_per_second': 518.397, 'eval_steps_per_second': 8.298, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.5

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.33799171447753906, 'eval_accuracy': 0.8503200393894633, 'eval_precision': 0.5746421267893661, 'eval_recall': 0.7453580901856764, 'eval_f1': 0.648960739030023, 'eval_pr_auc': 0.6885386667968322, 'eval_runtime': 3.9606, 'eval_samples_per_second': 512.797, 'eval_steps_per_second': 8.08, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.5

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3151129186153412, 'eval_accuracy': 0.8606639839034205, 'eval_precision': 0.605072463768116, 'eval_recall': 0.8498727735368957, 'eval_f1': 0.7068783068783069, 'eval_pr_auc': 0.792506962852345, 'eval_runtime': 3.9345, 'eval_samples_per_second': 505.28, 'eval_steps_per_second': 8.133, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.5

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3170066773891449, 'eval_accuracy': 0.86839481555334, 'eval_precision': 0.6383442265795207, 'eval_recall': 0.7493606138107417, 'eval_f1': 0.6894117647058824, 'eval_pr_auc': 0.7327777746791888, 'eval_runtime': 3.9884, 'eval_samples_per_second': 502.964, 'eval_steps_per_second': 8.023, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.25

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3432562053203583, 'eval_accuracy': 0.8568558513309894, 'eval_precision': 0.6123711340206186, 'eval_recall': 0.7538071065989848, 'eval_f1': 0.6757679180887372, 'eval_pr_auc': 0.7292436005557559, 'eval_runtime': 3.9828, 'eval_samples_per_second': 499.902, 'eval_steps_per_second': 8.035, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.25

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3347901403903961, 'eval_accuracy': 0.8449224612306153, 'eval_precision': 0.588469184890656, 'eval_recall': 0.7418546365914787, 'eval_f1': 0.656319290465632, 'eval_pr_auc': 0.7261076816095887, 'eval_runtime': 3.9397, 'eval_samples_per_second': 507.393, 'eval_steps_per_second': 8.122, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.25

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3433932363986969, 'eval_accuracy': 0.8458887247661251, 'eval_precision': 0.5680851063829787, 'eval_recall': 0.7082228116710876, 'eval_f1': 0.6304604486422668, 'eval_pr_auc': 0.6953357656036366, 'eval_runtime': 3.9841, 'eval_samples_per_second': 509.782, 'eval_steps_per_second': 8.032, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.25

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3430943191051483, 'eval_accuracy': 0.8395372233400402, 'eval_precision': 0.5610561056105611, 'eval_recall': 0.8651399491094147, 'eval_f1': 0.6806806806806807, 'eval_pr_auc': 0.7699621144629135, 'eval_runtime': 3.947, 'eval_samples_per_second': 503.676, 'eval_steps_per_second': 8.107, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.25

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.32484912872314453, 'eval_accuracy': 0.8614157527417746, 'eval_precision': 0.6146044624746451, 'eval_recall': 0.7749360613810742, 'eval_f1': 0.6855203619909502, 'eval_pr_auc': 0.7234912990751591, 'eval_runtime': 3.9017, 'eval_samples_per_second': 514.134, 'eval_steps_per_second': 8.202, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4024750888347626, 'eval_accuracy': 0.8036162732295329, 'eval_precision': 0.5024077046548957, 'eval_recall': 0.7944162436548223, 'eval_f1': 0.615535889872173, 'eval_pr_auc': 0.6566574481128548, 'eval_runtime': 3.9358, 'eval_samples_per_second': 505.864, 'eval_steps_per_second': 8.13, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3878324031829834, 'eval_accuracy': 0.8009004502251126, 'eval_precision': 0.5007923930269413, 'eval_recall': 0.7919799498746867, 'eval_f1': 0.6135922330097088, 'eval_pr_auc': 0.6708860728355825, 'eval_runtime': 3.9503, 'eval_samples_per_second': 506.04, 'eval_steps_per_second': 8.101, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3905806541442871, 'eval_accuracy': 0.810930576070901, 'eval_precision': 0.49417637271214643, 'eval_recall': 0.7877984084880637, 'eval_f1': 0.6073619631901841, 'eval_pr_auc': 0.639955453054173, 'eval_runtime': 3.959, 'eval_samples_per_second': 513.007, 'eval_steps_per_second': 8.083, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.37112078070640564, 'eval_accuracy': 0.8199195171026157, 'eval_precision': 0.5263157894736842, 'eval_recall': 0.8905852417302799, 'eval_f1': 0.6616257088846881, 'eval_pr_auc': 0.7564736421808977, 'eval_runtime': 3.8753, 'eval_samples_per_second': 512.995, 'eval_steps_per_second': 8.257, 'epoch': 10.0}

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.36656680703163147, 'eval_accuracy': 0.82901296111665, 'eval_precision': 0.5398671096345515, 'eval_recall': 0.8312020460358056, 'eval_f1': 0.6545820745216515, 'eval_pr_auc': 0.7090680969210164, 'eval_runtime': 3.9222, 'eval_samples_per_second': 511.45, 'eval_steps_per_second': 8.159, 'epoch': 10.0}

Evaluation Results

In [ ]:
train_imgs, train_dx = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.3

with open('/content/drive/MyDrive/Thesis/isic2018_fine_tuning_vit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
  val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

  print(f"Prop: {prop}")
  model = ViTForImageClassification.from_pretrained(
      model_name,
      num_labels=2,
      ignore_mismatched_sizes=True
  )

  # Freeze the whole ViT backbone first
  for param in model.vit.parameters():
      param.requires_grad = False

  layers = model.vit.encoder.layer
  n_layers = len(layers)
  print(f"Number of layers: {n_layers}")
  n_unfreeze = max(1, int(n_layers * prop))

  for layer in layers[-n_unfreeze:]:
      for param in layer.parameters():
          param.requires_grad = True

  # Keep classifier trainable
  for param in model.classifier.parameters():
      param.requires_grad = True

  # Train the model
  training_args = TrainingArguments(
      output_dir="./trains",
      per_device_train_batch_size=64,
      per_device_eval_batch_size=64,
      eval_strategy="epoch",
      save_strategy="epoch",
      logging_strategy="epoch",
      num_train_epochs=10,
      learning_rate=1e-5,
      save_total_limit=2,
      remove_unused_columns=False,
      load_best_model_at_end=True,
      metric_for_best_model="pr_auc",
      greater_is_better=True,
      dataloader_num_workers=8,
      dataloader_pin_memory=True,
      fp16=torch.cuda.is_available(),
      report_to="none",
      disable_tqdm=False,
  )

  trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics
  )

  trainer.train()

  eval_results = trainer.evaluate()

  print(eval_results)

  writer.writerow([
      prop,
      eval_results.get("eval_accuracy"),
      eval_results.get("eval_precision"),
      eval_results.get("eval_recall"),
      eval_results.get("eval_f1"),
      eval_results.get("eval_pr_auc"),
  ])

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...
Prop: 0.3

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: google/vit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3698216676712036, 'eval_accuracy': 0.8379629629629629, 'eval_precision': 0.5756097560975609, 'eval_recall': 0.7687296416938111, 'eval_f1': 0.6582984658298466, 'eval_pr_auc': 0.7222507381218515, 'eval_runtime': 3.207, 'eval_samples_per_second': 471.465, 'eval_steps_per_second': 7.484, 'epoch': 10.0}

### Swin Transformers

Fine Tuning

In [ ]:
model_names = ["microsoft/swin-base-patch4-window7-224-in22k",
               "microsoft/swin-small-patch4-window7-224",
               "microsoft/swin-tiny-patch4-window7-224"]

img_paths, dx = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('/content/drive/MyDrive/Thesis/isic2018_fine_tuning_swin.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for model_name in model_names:
    for prop in [0.75, 0.5, 0.25, 0]:
      print(f"Prop: {prop}")
      for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, img_paths)):
        train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
        train_dx, val_dx = dx[train_idx], dx[val_idx]
        train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

        # Get Preprocessed Data
        image_processor = AutoImageProcessor.from_pretrained(model_name)
        train_transform, val_transform = preprocess(image_processor)
        train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
        val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

        model = AutoModelForImageClassification.from_pretrained(
            model_name,
            num_labels=2,
            ignore_mismatched_sizes=True
        )

        for param in model.swin.parameters():
            param.requires_grad = False

        # Flatten all blocks across stages
        all_blocks = []
        for stage in model.swin.encoder.layers:
            all_blocks.extend(stage.blocks)  # 'blocks' contains the transformer blocks

        n_blocks = len(all_blocks)
        print(f"Number of transformer blocks: {n_blocks}")

        n_unfreeze = max(1, int(n_blocks * prop))  # e.g., prop=0.25
        for block in all_blocks[-n_unfreeze:]:
            for param in block.parameters():
                param.requires_grad = True

        # Keep classifier trainable
        for param in model.classifier.parameters():
            param.requires_grad = True

        # Train the model
        training_args = TrainingArguments(
            output_dir="./trains",
            per_device_train_batch_size=64,
            per_device_eval_batch_size=64,
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            num_train_epochs=10,
            learning_rate=1e-5,
            save_total_limit=2,
            remove_unused_columns=False,
            load_best_model_at_end=True,
            metric_for_best_model="pr_auc",
            greater_is_better=True,
            dataloader_num_workers=8,
            dataloader_pin_memory=True,
            fp16=torch.cuda.is_available(),
            report_to="none",
            disable_tqdm=False,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics
        )

        trainer.train()

        eval_results = trainer.evaluate()

        print(eval_results)

        writer.writerow([model_name] + [
            prop,
            eval_results.get("eval_accuracy"),
            eval_results.get("eval_precision"),
            eval_results.get("eval_recall"),
            eval_results.get("eval_f1"),
            eval_results.get("eval_pr_auc"),
        ])

ISIC 2018 Training Dataset...
Prop: 0.3

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2714843153953552, 'eval_accuracy': 0.8976535197204194, 'eval_precision': 0.7084233261339092, 'eval_recall': 0.8241206030150754, 'eval_f1': 0.7619047619047619, 'eval_pr_auc': 0.8378579532400359, 'eval_runtime': 6.7576, 'eval_samples_per_second': 296.406, 'eval_steps_per_second': 4.735, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.24431800842285156, 'eval_accuracy': 0.9011482775836246, 'eval_precision': 0.750599520383693, 'eval_recall': 0.769041769041769, 'eval_f1': 0.7597087378640777, 'eval_pr_auc': 0.8543406359239333, 'eval_runtime': 6.74, 'eval_samples_per_second': 297.183, 'eval_steps_per_second': 4.748, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.23875243961811066, 'eval_accuracy': 0.9051422865701447, 'eval_precision': 0.7023255813953488, 'eval_recall': 0.8296703296703297, 'eval_f1': 0.760705289672544, 'eval_pr_auc': 0.8386576529121592, 'eval_runtime': 6.6633, 'eval_samples_per_second': 300.601, 'eval_steps_per_second': 4.802, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.25427502393722534, 'eval_accuracy': 0.9056415376934598, 'eval_precision': 0.7082405345211581, 'eval_recall': 0.8457446808510638, 'eval_f1': 0.7709090909090909, 'eval_pr_auc': 0.8377345736756157, 'eval_runtime': 6.7739, 'eval_samples_per_second': 295.692, 'eval_steps_per_second': 4.724, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.25366532802581787, 'eval_accuracy': 0.9011482775836246, 'eval_precision': 0.7425287356321839, 'eval_recall': 0.7897310513447433, 'eval_f1': 0.7654028436018957, 'eval_pr_auc': 0.8458924739909987, 'eval_runtime': 6.734, 'eval_samples_per_second': 297.447, 'eval_steps_per_second': 4.752, 'epoch': 10.0}
Prop: 0.2

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2725750505924225, 'eval_accuracy': 0.889166250624064, 'eval_precision': 0.6774193548387096, 'eval_recall': 0.8442211055276382, 'eval_f1': 0.7516778523489933, 'eval_pr_auc': 0.8287777487651219, 'eval_runtime': 6.7586, 'eval_samples_per_second': 296.363, 'eval_steps_per_second': 4.735, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2583383619785309, 'eval_accuracy': 0.8866699950074888, 'eval_precision': 0.6923076923076923, 'eval_recall': 0.7960687960687961, 'eval_f1': 0.7405714285714285, 'eval_pr_auc': 0.8399700341671575, 'eval_runtime': 6.7611, 'eval_samples_per_second': 296.252, 'eval_steps_per_second': 4.733, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.26004695892333984, 'eval_accuracy': 0.8866699950074888, 'eval_precision': 0.6454352441613588, 'eval_recall': 0.8351648351648352, 'eval_f1': 0.7281437125748503, 'eval_pr_auc': 0.82402985567411, 'eval_runtime': 6.7313, 'eval_samples_per_second': 297.566, 'eval_steps_per_second': 4.754, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.27579042315483093, 'eval_accuracy': 0.8851722416375437, 'eval_precision': 0.646, 'eval_recall': 0.8590425531914894, 'eval_f1': 0.7374429223744292, 'eval_pr_auc': 0.8196450046514135, 'eval_runtime': 6.7557, 'eval_samples_per_second': 296.492, 'eval_steps_per_second': 4.737, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2688086926937103, 'eval_accuracy': 0.8826759860209685, 'eval_precision': 0.6804979253112033, 'eval_recall': 0.8019559902200489, 'eval_f1': 0.7362514029180696, 'eval_pr_auc': 0.8293575874221929, 'eval_runtime': 6.793, 'eval_samples_per_second': 294.864, 'eval_steps_per_second': 4.711, 'epoch': 10.0}
Prop: 0.1

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.29942265152931213, 'eval_accuracy': 0.872191712431353, 'eval_precision': 0.6309963099630996, 'eval_recall': 0.8592964824120602, 'eval_f1': 0.7276595744680852, 'eval_pr_auc': 0.8078272756219448, 'eval_runtime': 6.5655, 'eval_samples_per_second': 305.082, 'eval_steps_per_second': 4.874, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2728702425956726, 'eval_accuracy': 0.8776834747878183, 'eval_precision': 0.6575875486381323, 'eval_recall': 0.8304668304668305, 'eval_f1': 0.7339847991313789, 'eval_pr_auc': 0.8281296119232386, 'eval_runtime': 6.8195, 'eval_samples_per_second': 293.717, 'eval_steps_per_second': 4.692, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.28322336077690125, 'eval_accuracy': 0.8691962056914628, 'eval_precision': 0.5977011494252874, 'eval_recall': 0.8571428571428571, 'eval_f1': 0.7042889390519187, 'eval_pr_auc': 0.8123040935950104, 'eval_runtime': 6.7151, 'eval_samples_per_second': 298.284, 'eval_steps_per_second': 4.765, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.29905930161476135, 'eval_accuracy': 0.8681977034448327, 'eval_precision': 0.6014492753623188, 'eval_recall': 0.8829787234042553, 'eval_f1': 0.7155172413793104, 'eval_pr_auc': 0.8035672496623345, 'eval_runtime': 6.9762, 'eval_samples_per_second': 287.119, 'eval_steps_per_second': 4.587, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.29712334275245667, 'eval_accuracy': 0.8612081877184223, 'eval_precision': 0.6219739292364991, 'eval_recall': 0.8166259168704156, 'eval_f1': 0.7061310782241015, 'eval_pr_auc': 0.8105068236769601, 'eval_runtime': 6.7298, 'eval_samples_per_second': 297.631, 'eval_steps_per_second': 4.755, 'epoch': 10.0}
Prop: 0.3

preprocessor_config.json:   0%|          | 0.00/255 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/199M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

model.safetensors:   0%|          | 0.00/199M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3192692697048187, 'eval_accuracy': 0.8666999500748876, 'eval_precision': 0.6291913214990138, 'eval_recall': 0.8015075376884422, 'eval_f1': 0.7049723756906078, 'eval_pr_auc': 0.7416534052399693, 'eval_runtime': 5.0523, 'eval_samples_per_second': 396.451, 'eval_steps_per_second': 6.334, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.30239975452423096, 'eval_accuracy': 0.8731902146779831, 'eval_precision': 0.6577319587628866, 'eval_recall': 0.7837837837837838, 'eval_f1': 0.7152466367713004, 'eval_pr_auc': 0.7902600654277042, 'eval_runtime': 4.9959, 'eval_samples_per_second': 400.929, 'eval_steps_per_second': 6.405, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.2975444495677948, 'eval_accuracy': 0.8676984523215178, 'eval_precision': 0.6050955414012739, 'eval_recall': 0.782967032967033, 'eval_f1': 0.6826347305389222, 'eval_pr_auc': 0.7699642326160282, 'eval_runtime': 4.8823, 'eval_samples_per_second': 410.255, 'eval_steps_per_second': 6.554, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3042895495891571, 'eval_accuracy': 0.8597104343484773, 'eval_precision': 0.5897920604914934, 'eval_recall': 0.8297872340425532, 'eval_f1': 0.6895027624309392, 'eval_pr_auc': 0.7845108661279503, 'eval_runtime': 4.9145, 'eval_samples_per_second': 407.567, 'eval_steps_per_second': 6.511, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.30346471071243286, 'eval_accuracy': 0.8642036944583126, 'eval_precision': 0.6361829025844931, 'eval_recall': 0.78239608801956, 'eval_f1': 0.7017543859649122, 'eval_pr_auc': 0.7838613671753855, 'eval_runtime': 5.0268, 'eval_samples_per_second': 398.467, 'eval_steps_per_second': 6.366, 'epoch': 10.0}
Prop: 0.2

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.34063076972961426, 'eval_accuracy': 0.853220169745382, 'eval_precision': 0.5955882352941176, 'eval_recall': 0.8140703517587939, 'eval_f1': 0.6878980891719745, 'eval_pr_auc': 0.7183363285026697, 'eval_runtime': 4.8699, 'eval_samples_per_second': 411.302, 'eval_steps_per_second': 6.571, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.32005536556243896, 'eval_accuracy': 0.8502246630054917, 'eval_precision': 0.5974499089253188, 'eval_recall': 0.8058968058968059, 'eval_f1': 0.6861924686192469, 'eval_pr_auc': 0.7771044448740108, 'eval_runtime': 4.8969, 'eval_samples_per_second': 409.038, 'eval_steps_per_second': 6.535, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3221804201602936, 'eval_accuracy': 0.8522216674987518, 'eval_precision': 0.5653846153846154, 'eval_recall': 0.8076923076923077, 'eval_f1': 0.665158371040724, 'eval_pr_auc': 0.7379101666691931, 'eval_runtime': 5.0185, 'eval_samples_per_second': 399.125, 'eval_steps_per_second': 6.376, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.32821154594421387, 'eval_accuracy': 0.8462306540189716, 'eval_precision': 0.5600706713780919, 'eval_recall': 0.8430851063829787, 'eval_f1': 0.673036093418259, 'eval_pr_auc': 0.7629847795390018, 'eval_runtime': 5.0275, 'eval_samples_per_second': 398.407, 'eval_steps_per_second': 6.365, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3421497344970703, 'eval_accuracy': 0.8332501248127808, 'eval_precision': 0.5643224699828473, 'eval_recall': 0.80440097799511, 'eval_f1': 0.6633064516129032, 'eval_pr_auc': 0.7627293169739394, 'eval_runtime': 4.9227, 'eval_samples_per_second': 406.894, 'eval_steps_per_second': 6.501, 'epoch': 10.0}
Prop: 0.1

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.36062994599342346, 'eval_accuracy': 0.8342486270594108, 'eval_precision': 0.5574912891986062, 'eval_recall': 0.8040201005025126, 'eval_f1': 0.6584362139917695, 'eval_pr_auc': 0.6985681921596076, 'eval_runtime': 5.083, 'eval_samples_per_second': 394.06, 'eval_steps_per_second': 6.296, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3462359607219696, 'eval_accuracy': 0.8392411382925612, 'eval_precision': 0.571912013536379, 'eval_recall': 0.8304668304668305, 'eval_f1': 0.6773547094188377, 'eval_pr_auc': 0.7565215121379466, 'eval_runtime': 5.0577, 'eval_samples_per_second': 396.032, 'eval_steps_per_second': 6.327, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3557971119880676, 'eval_accuracy': 0.8312531203195207, 'eval_precision': 0.5218120805369127, 'eval_recall': 0.8543956043956044, 'eval_f1': 0.6479166666666667, 'eval_pr_auc': 0.7179763538329383, 'eval_runtime': 5.0355, 'eval_samples_per_second': 397.775, 'eval_steps_per_second': 6.355, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.36580750346183777, 'eval_accuracy': 0.8227658512231653, 'eval_precision': 0.5170731707317073, 'eval_recall': 0.8457446808510638, 'eval_f1': 0.6417759838546923, 'eval_pr_auc': 0.7295358522521791, 'eval_runtime': 5.0091, 'eval_samples_per_second': 399.87, 'eval_steps_per_second': 6.388, 'epoch': 10.0}

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-small-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.37144193053245544, 'eval_accuracy': 0.8077883175237144, 'eval_precision': 0.5190476190476191, 'eval_recall': 0.7995110024449877, 'eval_f1': 0.629451395572666, 'eval_pr_auc': 0.7365366871470185, 'eval_runtime': 4.8742, 'eval_samples_per_second': 410.943, 'eval_steps_per_second': 6.565, 'epoch': 10.0}
Prop: 0.3

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.31724846363067627, 'eval_accuracy': 0.8582126809785322, 'eval_precision': 0.6067415730337079, 'eval_recall': 0.8140703517587939, 'eval_f1': 0.6952789699570815, 'eval_pr_auc': 0.7604858615103466, 'eval_runtime': 3.7714, 'eval_samples_per_second': 531.109, 'eval_steps_per_second': 8.485, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.30336689949035645, 'eval_accuracy': 0.8686969545681478, 'eval_precision': 0.6353383458646616, 'eval_recall': 0.8304668304668305, 'eval_f1': 0.7199148029818956, 'eval_pr_auc': 0.783995016288865, 'eval_runtime': 3.7888, 'eval_samples_per_second': 528.663, 'eval_steps_per_second': 8.446, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3193417191505432, 'eval_accuracy': 0.8502246630054917, 'eval_precision': 0.5617760617760618, 'eval_recall': 0.7994505494505495, 'eval_f1': 0.6598639455782312, 'eval_pr_auc': 0.7529385056299046, 'eval_runtime': 3.735, 'eval_samples_per_second': 536.282, 'eval_steps_per_second': 8.568, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3114745020866394, 'eval_accuracy': 0.8671992011982027, 'eval_precision': 0.6045627376425855, 'eval_recall': 0.8457446808510638, 'eval_f1': 0.70509977827051, 'eval_pr_auc': 0.7709442542138343, 'eval_runtime': 3.7912, 'eval_samples_per_second': 528.325, 'eval_steps_per_second': 8.441, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3170216679573059, 'eval_accuracy': 0.8567149276085871, 'eval_precision': 0.6129629629629629, 'eval_recall': 0.8092909535452323, 'eval_f1': 0.6975763962065332, 'eval_pr_auc': 0.7811424251668329, 'eval_runtime': 3.769, 'eval_samples_per_second': 531.442, 'eval_steps_per_second': 8.49, 'epoch': 10.0}
Prop: 0.2

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.33583515882492065, 'eval_accuracy': 0.8427358961557664, 'eval_precision': 0.5726795096322241, 'eval_recall': 0.821608040201005, 'eval_f1': 0.6749226006191951, 'eval_pr_auc': 0.7402067421840521, 'eval_runtime': 3.7572, 'eval_samples_per_second': 533.106, 'eval_steps_per_second': 8.517, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3255752921104431, 'eval_accuracy': 0.854218671992012, 'eval_precision': 0.6014109347442681, 'eval_recall': 0.8378378378378378, 'eval_f1': 0.7002053388090349, 'eval_pr_auc': 0.7540720991661427, 'eval_runtime': 3.7885, 'eval_samples_per_second': 528.703, 'eval_steps_per_second': 8.447, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3465003967285156, 'eval_accuracy': 0.8372441337993011, 'eval_precision': 0.5341726618705036, 'eval_recall': 0.8159340659340659, 'eval_f1': 0.6456521739130435, 'eval_pr_auc': 0.7262807550358809, 'eval_runtime': 3.7419, 'eval_samples_per_second': 535.284, 'eval_steps_per_second': 8.552, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3349473178386688, 'eval_accuracy': 0.8497254118821768, 'eval_precision': 0.566607460035524, 'eval_recall': 0.848404255319149, 'eval_f1': 0.6794462193823216, 'eval_pr_auc': 0.7450294625512155, 'eval_runtime': 3.7647, 'eval_samples_per_second': 532.043, 'eval_steps_per_second': 8.5, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.33847177028656006, 'eval_accuracy': 0.8372441337993011, 'eval_precision': 0.5737122557726465, 'eval_recall': 0.7897310513447433, 'eval_f1': 0.6646090534979424, 'eval_pr_auc': 0.7595725711636823, 'eval_runtime': 3.674, 'eval_samples_per_second': 545.189, 'eval_steps_per_second': 8.71, 'epoch': 10.0}
Prop: 0.1

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.38545897603034973, 'eval_accuracy': 0.8147778332501248, 'eval_precision': 0.521193092621664, 'eval_recall': 0.8341708542713567, 'eval_f1': 0.6415458937198067, 'eval_pr_auc': 0.6928293321542768, 'eval_runtime': 3.8016, 'eval_samples_per_second': 526.89, 'eval_steps_per_second': 8.418, 'epoch': 10.0}

'The read operation timed out' thrown while requesting HEAD https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/resolve/main/processor_config.json
WARNING:huggingface_hub.utils._http:'The read operation timed out' thrown while requesting HEAD https://huggingface.co/microsoft/swin-tiny-patch4-window7-224/resolve/main/processor_config.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.37146154046058655, 'eval_accuracy': 0.8202695956065901, 'eval_precision': 0.5368916797488226, 'eval_recall': 0.8402948402948403, 'eval_f1': 0.6551724137931034, 'eval_pr_auc': 0.6960309322916403, 'eval_runtime': 3.7883, 'eval_samples_per_second': 528.736, 'eval_steps_per_second': 8.447, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3839544653892517, 'eval_accuracy': 0.817773339990015, 'eval_precision': 0.4991896272285251, 'eval_recall': 0.8461538461538461, 'eval_f1': 0.6279306829765545, 'eval_pr_auc': 0.6822086970902143, 'eval_runtime': 3.6538, 'eval_samples_per_second': 548.191, 'eval_steps_per_second': 8.758, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3789142966270447, 'eval_accuracy': 0.8127808287568647, 'eval_precision': 0.5007776049766719, 'eval_recall': 0.8563829787234043, 'eval_f1': 0.6319921491658489, 'eval_pr_auc': 0.7093376389582762, 'eval_runtime': 3.8229, 'eval_samples_per_second': 523.954, 'eval_steps_per_second': 8.371, 'epoch': 10.0}

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 12

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3838196098804474, 'eval_accuracy': 0.8052920619071393, 'eval_precision': 0.514866979655712, 'eval_recall': 0.80440097799511, 'eval_f1': 0.6278625954198473, 'eval_pr_auc': 0.7184951015074282, 'eval_runtime': 3.8156, 'eval_samples_per_second': 524.948, 'eval_steps_per_second': 8.387, 'epoch': 10.0}

Evaluate

In [ ]:
model_names = ["microsoft/swin-base-patch4-window7-224-in22k",
               "microsoft/swin-small-patch4-window7-224",
               "microsoft/swin-tiny-patch4-window7-224"]


train_imgs, train_dx = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.3

with open('/content/drive/MyDrive/Thesis/isic2018_swin.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for model_name in model_names:

    # Get Preprocessed Data
    image_processor = AutoImageProcessor.from_pretrained(model_name)
    train_transform, val_transform = preprocess(image_processor)
    train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
    val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

    model = AutoModelForImageClassification.from_pretrained(
        model_name,
        num_labels=2,
        ignore_mismatched_sizes=True
    )

    for param in model.swin.parameters():
        param.requires_grad = False

    # Flatten all blocks across stages
    all_blocks = []
    for stage in model.swin.encoder.layers:
        all_blocks.extend(stage.blocks)  # 'blocks' contains the transformer blocks

    n_blocks = len(all_blocks)
    print(f"Number of transformer blocks: {n_blocks}")

    n_unfreeze = max(1, int(n_blocks * prop))  # e.g., prop=0.25
    for block in all_blocks[-n_unfreeze:]:
        for param in block.parameters():
            param.requires_grad = True

    # Keep classifier trainable
    for param in model.classifier.parameters():
        param.requires_grad = True

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    eval_results = trainer.evaluate()

    print(eval_results)

    writer.writerow([model_name] + [
        prop,
        eval_results.get("eval_accuracy"),
        eval_results.get("eval_precision"),
        eval_results.get("eval_recall"),
        eval_results.get("eval_f1"),
        eval_results.get("eval_pr_auc"),
    ])

Getting ISIC...
Getting MILK...
Combining Datasets...
Number images with skin tone 0_0: 5146
Number images with skin tone 0_1: 4201
Number images with skin tone 0_2: 1674
Number images with skin tone 1_0: 3732
Number images with skin tone 1_1: 5521
Number images with skin tone 1_2: 81

Loading weights:   0%|          | 0/449 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-base-patch4-window7-224-in22k
Key               | Status   |
------------------+----------+-------------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841, 1024]) vs model:torch.Size([2, 1024])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([21841]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of transformer blocks: 24

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt:

### DeiT

Fine Tuning

In [ ]:
model_names = ["facebook/deit-base-patch16-224",
                "facebook/deit-small-patch16-224",
                "facebook/deit-tiny-patch16-224"]

img_paths, dx = get_train_isic2018()
img_paths = np.array(img_paths)
dx = np.array(dx)

with open('/content/drive/MyDrive/Thesis/isic2018_fine_tuning_deit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Model", "Unfrozen Layers", "Accuracy", "Precision", "Recall", "F1", "PR-AUC"])

  for model_name in model_names:
    for prop in [0.75, 0.5, 0.25, 0]:
      for fold, (train_idx, val_idx) in enumerate(sgkf.split(img_paths, dx, img_paths)):
        train_imgs, val_imgs = img_paths[train_idx], img_paths[val_idx]
        train_dx, val_dx = dx[train_idx], dx[val_idx]
        train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)

        # Get Preprocessed Data
        image_processor = AutoImageProcessor.from_pretrained(model_name)
        train_transform, val_transform = preprocess(image_processor)
        train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
        val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

        print(f"Prop: {prop}")
        model = AutoModelForImageClassification.from_pretrained(
            model_name,
            num_labels=2,
            ignore_mismatched_sizes=True
        )

        # Freeze the whole ViT backbone first
        for param in model.vit.parameters():
            param.requires_grad = False

        layers = model.vit.encoder.layer
        n_layers = len(layers)
        print(f"Number of layers: {n_layers}")
        n_unfreeze = max(1, int(n_layers * prop))

        for layer in layers[-n_unfreeze:]:
            for param in layer.parameters():
                param.requires_grad = True

        # Keep classifier trainable
        for param in model.classifier.parameters():
            param.requires_grad = True

        # Train the model
        training_args = TrainingArguments(
            output_dir="./trains",
            per_device_train_batch_size=64,
            per_device_eval_batch_size=64,
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            num_train_epochs=10,
            learning_rate=1e-5,
            save_total_limit=2,
            remove_unused_columns=False,
            load_best_model_at_end=True,
            metric_for_best_model="pr_auc",
            greater_is_better=True,
            dataloader_num_workers=8,
            dataloader_pin_memory=True,
            fp16=torch.cuda.is_available(),
            report_to="none",
            disable_tqdm=False,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics
        )

        trainer.train()

        eval_results = trainer.evaluate()

        print(eval_results)

        writer.writerow([
            model_name,
            prop,
            eval_results.get("eval_accuracy"),
            eval_results.get("eval_precision"),
            eval_results.get("eval_recall"),
            eval_results.get("eval_f1"),
            eval_results.get("eval_pr_auc"),
        ])

ISIC 2018 Training Dataset...

ValueError: too many values to unpack (expected 2)

Evaluate

In [ ]:
model_names = ["facebook/deit-base-patch16-224",
                "facebook/deit-small-patch16-224",
                "facebook/deit-tiny-patch16-224"]

train_imgs, train_dx = get_train_isic2018()
train_imgs, train_dx, _, _ = oversample_minority(train_imgs, train_dx)
val_imgs, val_dx = get_test_isic2018()

train_imgs = np.array(train_imgs)
train_dx = np.array(train_dx)
val_imgs = np.array(val_imgs)
val_dx = np.array(val_dx)

prop = 0.3

with open('/content/drive/MyDrive/Thesis/isic2018_deit.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Model", "Precision", "Recall", "F1", "PR-AUC"])

  for model_name in model_names:
    # Get Preprocessed Data
    image_processor = AutoImageProcessor.from_pretrained(model_name)
    train_transform, val_transform = preprocess(image_processor)
    train_ds = SkinLesionDataset(train_dx, train_imgs, transform=train_transform)
    val_ds = SkinLesionDataset(val_dx, val_imgs, transform=val_transform)

    print(f"Prop: {prop}")
    model = AutoModelForImageClassification.from_pretrained(
        model_name,
        num_labels=2,
        ignore_mismatched_sizes=True
    )

    # Freeze the whole ViT backbone first
    for param in model.vit.parameters():
        param.requires_grad = False

    layers = model.vit.encoder.layer
    n_layers = len(layers)
    print(f"Number of layers: {n_layers}")
    n_unfreeze = max(1, int(n_layers * prop))

    for layer in layers[-n_unfreeze:]:
        for param in layer.parameters():
            param.requires_grad = True

    # Keep classifier trainable
    for param in model.classifier.parameters():
        param.requires_grad = True

    # Train the model
    training_args = TrainingArguments(
        output_dir="./trains",
        per_device_train_batch_size=64,
        per_device_eval_batch_size=64,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_strategy="epoch",
        num_train_epochs=10,
        learning_rate=1e-5,
        save_total_limit=2,
        remove_unused_columns=False,
        load_best_model_at_end=True,
        metric_for_best_model="pr_auc",
        greater_is_better=True,
        dataloader_num_workers=8,
        dataloader_pin_memory=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        disable_tqdm=False,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics
    )

    trainer.train()

    eval_results = trainer.evaluate()

    print(eval_results)

    writer.writerow([
        model_name,
        eval_results.get("eval_precision"),
        eval_results.get("eval_recall"),
        eval_results.get("eval_f1"),
        eval_results.get("eval_pr_auc"),
    ])

ISIC 2018 Training Dataset...
ISIC 2018 Test Dataset...

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.3

pytorch_model.bin:   0%|          | 0.00/346M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: facebook/deit-base-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

model.safetensors:   0%|          | 0.00/346M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3594415783882141, 'eval_accuracy': 0.8525132275132276, 'eval_precision': 0.6111111111111112, 'eval_recall': 0.752442996742671, 'eval_f1': 0.6744525547445256, 'eval_pr_auc': 0.7325530441732336, 'eval_runtime': 3.1818, 'eval_samples_per_second': 475.196, 'eval_steps_per_second': 7.543, 'epoch': 10.0}

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.3

pytorch_model.bin:   0%|          | 0.00/88.3M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: facebook/deit-small-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 384]) vs model:torch.Size([2, 384])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

model.safetensors:   0%|          | 0.00/88.2M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.3981444835662842, 'eval_accuracy': 0.8167989417989417, 'eval_precision': 0.532608695652174, 'eval_recall': 0.7980456026058632, 'eval_f1': 0.6388526727509778, 'eval_pr_auc': 0.6774124893415487, 'eval_runtime': 2.0119, 'eval_samples_per_second': 751.518, 'eval_steps_per_second': 11.929, 'epoch': 10.0}

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Fast image processor class <class 'transformers.models.vit.image_processing_vit_fast.ViTImageProcessorFast'> is available for this model. Using slow image processor class. To use the fast image processor class set `use_fast=True`.

Prop: 0.3

pytorch_model.bin:   0%|          | 0.00/23.0M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

ViTForImageClassification LOAD REPORT from: facebook/deit-tiny-patch16-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 192]) vs model:torch.Size([2, 192])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Number of layers: 12

model.safetensors:   0%|          | 0.00/22.9M [00:00<?, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

{'eval_loss': 0.4467390775680542, 'eval_accuracy': 0.7896825396825397, 'eval_precision': 0.4892367906066536, 'eval_recall': 0.8143322475570033, 'eval_f1': 0.6112469437652812, 'eval_pr_auc': 0.622017376591974, 'eval_runtime': 1.899, 'eval_samples_per_second': 796.205, 'eval_steps_per_second': 12.638, 'epoch': 10.0}

# Adversarial Network

## Gradient Reversal Layer

In [ ]:
from torch.autograd import Function
import torch

sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

class GradReverse(Function):
    @staticmethod
    def forward(ctx, x, lambda_):
        ctx.lambda_ = lambda_
        return x.view_as(x)

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.lambda_ * grad_output, None

def grad_reverse(x, lambda_=1.0):
    return GradReverse.apply(x, lambda_)

## Metrics

In [ ]:
!pip install evaluate
import evaluate
import numpy as np
from sklearn.metrics import average_precision_score

accuracy = evaluate.load("accuracy")
precision = evaluate.load("precision")
recall = evaluate.load("recall")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    predictions, label_ids = eval_pred

    main_logits, adv_logits = predictions
    main_labels, skin_labels = label_ids

    main_preds = np.argmax(main_logits, axis=1)
    adv_preds = np.argmax(adv_logits, axis=1)

    print("Adv pred counts:", np.bincount(adv_preds))
    print("Adv true counts:", np.bincount(skin_labels))

    # stable softmax for PR-AUC
    shifted = main_logits - np.max(main_logits, axis=1, keepdims=True)
    main_probs = np.exp(shifted) / np.exp(shifted).sum(axis=1, keepdims=True)

    metrics = {}

    # Main task metrics
    metrics["accuracy"] = accuracy.compute(
        predictions=main_preds, references=main_labels
    )["accuracy"]
    metrics["precision"] = precision.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["precision"]
    metrics["recall"] = recall.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["recall"]
    metrics["f1"] = f1.compute(
        predictions=main_preds, references=main_labels, average="binary"
    )["f1"]
    metrics["pr_auc"] = average_precision_score(main_labels, main_probs[:, 1])

    # Adversarial task metrics
    metrics["adv_accuracy"] = accuracy.compute(
        predictions=adv_preds, references=skin_labels
    )["accuracy"]

    return metrics

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.10.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.1 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

## Prepare Data

In [ ]:
from torch.utils.data import Dataset
from PIL import Image
class AdversarialSkinLesionDataset(Dataset):
    def __init__(self, labels, skin_tones, img_paths, transform=None):
        self.labels = labels
        self.img_paths = img_paths
        self.transform = transform
        self.skin_tones = skin_tones

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        image = Image.open(self.img_paths[idx]).convert("RGB")
        label = torch.tensor(self.labels[idx], dtype=torch.long)
        skin_tone = torch.tensor(self.skin_tones[idx], dtype=torch.long)

        if self.transform is not None:
            image = self.transform(image)

        return {
            "pixel_values": image,
            "labels": label,
            "skin_tone_labels": skin_tone
        }

from transformers import Trainer

class AdversarialTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(
            pixel_values=inputs["pixel_values"],
            labels=inputs.get("labels"),
            skin_tone_labels=inputs.get("skin_tone_labels"),
        )
        loss = outputs["loss"]
        return (loss, outputs) if return_outputs else loss

    def prediction_step(self, model, inputs, prediction_loss_only, ignore_keys=None):
        has_labels = "labels" in inputs and "skin_tone_labels" in inputs

        inputs = self._prepare_inputs(inputs)

        with torch.no_grad():
            outputs = model(
                pixel_values=inputs["pixel_values"],
                labels=inputs.get("labels"),
                skin_tone_labels=inputs.get("skin_tone_labels"),
            )

        loss = outputs["loss"].detach() if has_labels and outputs.get("loss") is not None else None

        if prediction_loss_only:
            return (loss, None, None)

        logits = (
            outputs["logits"].detach(),
            outputs["adversarial_logits"].detach(),
        )

        labels = None
        if has_labels:
            labels = (
                inputs["labels"].detach(),
                inputs["skin_tone_labels"].detach(),
            )

        return (loss, logits, labels)

## Swin Model with Adversarial Network

In [ ]:
import torch
from transformers import AutoModelForImageClassification

class SwinModelWithAdversarial(torch.nn.Module):
    def __init__(
        self,
        model_name,
        prop=0.75,
        num_labels=2,
        adv_classes=5,
        lambda_=0.0,
        loss_fn=torch.nn.CrossEntropyLoss(),
    ):
        super().__init__()

        self.model = AutoModelForImageClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            output_hidden_states=True,
            ignore_mismatched_sizes=True,
            output_attentions=True
        )

        self.loss_fn = loss_fn
        self.lambda_ = lambda_

        for param in self.model.swin.parameters():
            param.requires_grad = False

        all_blocks = []
        for stage in self.model.swin.encoder.layers:
            all_blocks.extend(stage.blocks)

        n_blocks = len(all_blocks)
        n_unfreeze = max(1, int(n_blocks * prop))

        for block in all_blocks[-n_unfreeze:]:
            for param in block.parameters():
                param.requires_grad = True

        for param in self.model.classifier.parameters():
            param.requires_grad = True

        hidden_size = self.model.config.hidden_size

        self.adversarial = torch.nn.Sequential(
            torch.nn.Linear(hidden_size, 128),
            torch.nn.GELU(),
            torch.nn.Linear(128, adv_classes),
        )

    def forward(
        self,
        pixel_values,
        labels=None,
        skin_tone_labels=None,
        output_attentions=False,
        output_hidden_states=True,
        return_dict=True,
    ):
        outputs = self.model(
            pixel_values=pixel_values,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

        features = outputs.hidden_states[-1].mean(dim=1)
        logits = outputs.logits

        reverse_features = grad_reverse(features, lambda_=self.lambda_)
        adversarial_logits = self.adversarial(reverse_features)

        prediction_loss = None
        adversarial_loss = None
        total_loss = None

        if labels is not None:
            labels = labels.view(-1).long()
            prediction_loss = self.loss_fn(logits, labels)

        if skin_tone_labels is not None:
            skin_tone_labels = skin_tone_labels.view(-1).long()
            adversarial_loss = self.loss_fn(adversarial_logits, skin_tone_labels)

        if prediction_loss is not None and adversarial_loss is not None:
            total_loss = prediction_loss + adversarial_loss
        elif prediction_loss is not None:
            total_loss = prediction_loss

        return {
            "loss": total_loss,
            "logits": logits,
            "adversarial_logits": adversarial_logits,
            "attentions": outputs.attentions,
            "hidden_states": outputs.hidden_states,
        }

Fine Tune Lambda

In [ ]:

from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

NUM_CLASSES = 3

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# -------------------------
# 1) Split off TEST set
# -------------------------
# 5 folds -> one fold is 20% test
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
trainval_idx, test_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

trainval_imgs = img_paths[trainval_idx]
trainval_dx = dx[trainval_idx]
trainval_skin_tones = skin_tones[trainval_idx]
trainval_patient_ids = patient_ids[trainval_idx]

trainval_strata = np.array([f"{d}_{s}" for d, s in zip(trainval_dx, trainval_skin_tones)])

# 4 folds -> one fold is 25% of trainval = 20% of original
sgkf = StratifiedGroupKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

with open(f'/content/drive/MyDrive/Thesis/swin_adv_fine_tune_{NUM_CLASSES}.csv', 'a', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Precision", "Recall", "F1", "PR-AUC", "Adversarial Accuracy", "Equal Opportuinity",
                   "Equalized Odds", "Demographic Parity"])

  # Get Preprocessed Data
  for lambda_ in [0.03, 0.04, 0.05, 0, 0.01, 0.02]:
    for fold, (train_idx, val_idx) in enumerate(sgkf.split(trainval_imgs, trainval_strata, trainval_patient_ids)):
        train_imgs, val_imgs = trainval_imgs[train_idx], trainval_imgs[val_idx]
        train_dx, val_dx = trainval_dx[train_idx], trainval_dx[val_idx]
        train_skin_tones, val_skin_tones = trainval_skin_tones[train_idx], trainval_skin_tones[val_idx]

        image_processor = AutoImageProcessor.from_pretrained(model_name)
        train_transform, val_transform = preprocess(image_processor)
        train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
        val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

        model = SwinModelWithAdversarial(model_name, lambda_=lambda_, adv_classes=NUM_CLASSES)

        # Train the model
        training_args = TrainingArguments(
            output_dir="./trains",
            per_device_train_batch_size=64,
            per_device_eval_batch_size=64,
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            num_train_epochs=5,
            learning_rate=1e-5,
            save_total_limit=2,
            remove_unused_columns=False,
            load_best_model_at_end=True,
            metric_for_best_model="pr_auc",
            greater_is_better=True,
            dataloader_num_workers=8,
            dataloader_pin_memory=True,
            fp16=torch.cuda.is_available(),
            report_to="none",
            disable_tqdm=False,
        )

        trainer = AdversarialTrainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            eval_dataset=val_ds,
            compute_metrics=compute_metrics
        )

        # Get the results on the validation dataset
        trainer.train()
        eval_results = trainer.evaluate()

        # Get the results for the light, medium, and dark datasets
        val_results = trainer.predict(val_ds)

        val_pred = np.argmax(val_results.predictions[0], axis=1)
        val_dx = np.array(val_dx)

        equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
        demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
        equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

        # Failsafe in case the runtime breaks
        print(eval_results)
        print("Equal Opportunity:", equal_opportunity)
        print("Demographic Parity:", demographic_parity)
        print("Equalized Odds:", equalized_odds)

        writer.writerow([
          model_name,
          lambda_,
          eval_results.get("eval_precision"),
          eval_results.get("eval_recall"),
          eval_results.get("eval_f1"),
          eval_results.get("eval_pr_auc"),
          eval_results.get("eval_adv_accuracy"),
          equal_opportunity,
          equalized_odds,
          demographic_parity,
        ])

Getting ISIC...
Getting MILK...
Combining Datasets...
Number images with skin tone 0_0: 5146
Number images with skin tone 0_1: 4201
Number images with skin tone 0_2: 1674
Number images with skin tone 1_0: 3732
Number images with skin tone 1_1: 5521
Number images with skin tone 1_2: 81

AttributeError: module 'torch.nn' has no attribute 'HingeLoss'

Evaluate

In [ ]:
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold

# os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
NUM_CLASSES = 2

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# -------------------------
# 1) Split off TEST set
# -------------------------
# 5 folds -> one fold is 20% test
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

# -------------------------
# 3) Verify no patient leakage
# -------------------------
assert set(train_patient_ids).isdisjoint(set(val_patient_ids))

print("Train:", len(train_imgs))
print("Val:", len(val_imgs))
print("No patient overlap across splits.")

with open('/content/drive/MyDrive/Thesis/swin_adversarial_fine_tune.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Fold", "Precision", "Recall", "F1", "PR-AUC",
                   "Light Precision", "Light Recall", "Light F1", "Light PR-AUC",
                   "Medium Precision", "Medium Recall", "Medium F1", "Medium PR-AUC",
                   "Dark Precision", "Dark Recall", "Dark F1", "Dark PR-AUC",])

  # Get Preprocessed Data
  image_processor = AutoImageProcessor.from_pretrained(model_name)
  train_transform, val_transform = preprocess(image_processor)
  train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
  val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

  model = SwinModelWithAdversarial(model_name, lambda_=0.035, adv_classes=NUM_CLASSES)

  # Train the model
  training_args = TrainingArguments(
      output_dir="./trains",
      per_device_train_batch_size=64,
      per_device_eval_batch_size=64,
      eval_strategy="epoch",
      save_strategy="epoch",
      logging_strategy="epoch",
      num_train_epochs=10,
      learning_rate=1e-5,
      save_total_limit=2,
      remove_unused_columns=False,
      load_best_model_at_end=True,
      metric_for_best_model="pr_auc",
      greater_is_better=True,
      dataloader_num_workers=8,
      dataloader_pin_memory=True,
      fp16=torch.cuda.is_available(),
      report_to="none",
      disable_tqdm=False,
  )

  trainer = AdversarialTrainer(
      model=model,
      args=training_args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics
  )

  # Get the results on the validation dataset
  trainer.train()
  eval_results = trainer.evaluate()

  # Get the results for the light, medium, and dark datasets
  val_results = trainer.predict(val_ds)
  val_pred = np.argmax(val_results.predictions[0], axis=1)
  val_dx = np.array(val_dx)

  equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
  demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
  equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones, agg="mean")

  print("Equal Opportunity:", equal_opportunity)
  print("Demographic Parity:", demographic_parity)
  print("Equalized Odds:", equalized_odds)

  # Failsafe in case the runtime breaks
  print(eval_results)

  writer.writerow([
    model_name,
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
    eval_results.get("eval_adv_accuracy"),
    equal_opportunity,
    equalized_odds,
    demographic_parity,
  ])

  # Save the model
  trainer.save_model('/content/drive/MyDrive/Thesis/models/swin_adversarial_0.03')
  trainer.save_state()

Getting ISIC...
Getting MILK...
Combining Datasets...
Number images with skin tone 0_0: 7912
Number images with skin tone 0_1: 3109
Number images with skin tone 1_0: 8801
Number images with skin tone 1_1: 533
Train: 16746
Val: 3609
No patient overlap across splits.

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Adv pred counts: [3557   52]
Adv true counts: [3084  525]
Adv pred counts: [3502  107]
Adv true counts: [3084  525]
Adv pred counts: [3454  155]
Adv true counts: [3084  525]
Adv pred counts: [3461  148]
Adv true counts: [3084  525]
Adv pred counts: [3503  106]
Adv true counts: [3084  525]
Adv pred counts: [3484  125]
Adv true counts: [3084  525]
Adv pred counts: [3302  307]
Adv true counts: [3084  525]
Adv pred counts: [3062  547]
Adv true counts: [3084  525]
Adv pred counts: [2895  714]
Adv true counts: [3084  525]
Adv pred counts: [2843  766]
Adv true counts: [3084  525]

Adv pred counts: [3062  547]
Adv true counts: [3084  525]
Adv pred counts: [3062  547]
Adv true counts: [3084  525]
Equal Opportunity: 0.20887564685588833
Demographic Parity: 0.4278765981100612
Equalized Odds: 0.16382013419694275
{'eval_loss': 1.0154168605804443, 'eval_accuracy': 0.8836242726517041, 'eval_precision': 0.8754359740906826, 'eval_recall': 0.9117799688635184, 'eval_f1': 0.8932384341637011, 'eval_pr_auc': 0.9394096868875713, 'eval_adv_accuracy': 0.7323358270989194, 'eval_runtime': 15.9459, 'eval_samples_per_second': 226.328, 'eval_steps_per_second': 3.575, 'epoch': 10.0}

Fariness Metrics

In [ ]:
img_paths, dx, skin_tones = get_fitzpatrick_datasets()
strata = [f"{a}_{b}" for a, b in zip(dx, skin_tones)]
train_imgs, val_imgs, train_dx, val_dx, train_skin_tones, val_skin_tones = train_test_split(img_paths, dx, skin_tones, test_size=0.2, random_state=42, stratify=strata)

model_names = [
    "swin_adversarial_0",
]

with open('/content/drive/MyDrive/Thesis/swin_fairness.csv', 'a', newline='') as csvfile:
    writer = csv.writer(csvfile)

    for model_name in model_names:
        save_path = f"/content/drive/MyDrive/Thesis/models/{model_name}"
        lambda_value = float(model_name.split("_")[-1])

        image_processor = AutoImageProcessor.from_pretrained(save_path)
        train_transform, val_transform = preprocess(image_processor)
        inputs = val_transform(images=val_imgs, return_tensors="pt")

        # Recreate model
        model = SwinModelWithAdversarial("microsoft/swin-tiny-patch4-window7-224", lambda_=lambda_value)

        # Load weights
        if os.path.exists(f"{save_path}/model.safetensors"):
            from safetensors.torch import load_file
            state_dict = load_file(f"{save_path}/model.safetensors")
        elif os.path.exists(f"{save_path}/pytorch_model.bin"):
            state_dict = torch.load(f"{save_path}/pytorch_model.bin", map_location="cpu")
        else:
            raise FileNotFoundError(f"No model file found in {save_path}")

        model.load_state_dict(state_dict)
        outputs = model(**inputs)

        print(outputs.attentions)

Getting ISIC...
----- ISIC -----
Number images: 10121
Number malignant images: 2066
Number benign images: 8055
Number images with skin tone 0: 6012
Number images with skin tone 1: 2538
Number images with skin tone 2: 1571
Getting MILK...
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
----- MILK -----
Number images: 10234
Number malignant images: 7268
Number benign images: 2966
Number skin tones: [0 1 2]
Getting MILK
---- Combined Datasets -----
Number images: 20355
Number malignant images: 9334
Number benign images: 11021
Number images with skin tone 0: 8878
Number images with skin tone 1: 9722
Number images with skin tone 2: 1755

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Adv pred counts: [1081  686    9]
Adv true counts: [1776]

Adv pred counts: [ 369 1517   58]
Adv true counts: [   0 1944]

Adv pred counts: [ 44  53 254]
Adv true counts: [  0   0 351]

# Oversampling

In [ ]:
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
!pip install fairlearn
from fairlearn.metrics import equalized_odds_difference, demographic_parity_difference, equal_opportunity_difference

model_name = "microsoft/swin-tiny-patch4-window7-224"

img_paths, dx, skin_tones, patient_ids = get_fitzpatrick_datasets()

# Convert to numpy arrays so indexing by split indices is easy
img_paths = np.array(img_paths)
dx = np.array(dx)
skin_tones = np.array(skin_tones)
patient_ids = np.array(patient_ids)

# Stratify on diagnosis + skin tone
strata = np.array([f"{d}_{s}" for d, s in zip(dx, skin_tones)])

# Create test dataset
sgkf_test = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, val_idx = next(sgkf_test.split(img_paths, strata, groups=patient_ids))

train_imgs = img_paths[train_idx]
val_imgs = img_paths[val_idx]

train_dx = dx[train_idx]
val_dx = dx[val_idx]

train_skin_tones = skin_tones[train_idx]
val_skin_tones = skin_tones[val_idx]

train_patient_ids = patient_ids[train_idx]
val_patient_ids = patient_ids[val_idx]

# Ensures no patient id leakage
assert set(train_patient_ids).isdisjoint(set(val_patient_ids))

# Oversample such that the same number of images in each strata
# NOTE: Most benign classes is in the light dataset and the most malignant classes is in the medium dataset

# Make each dataset have the same number of benign cases
light_benign_idx = np.where((train_skin_tones == 0) & (train_dx == 0))[0]
medium_benign_idx = np.where((train_skin_tones == 1) & (train_dx == 0))[0]
dark_benign_idx = np.where((train_skin_tones == 2) & (train_dx == 0))[0]

light_medium_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[medium_benign_idx]])
light_medium_dx = np.concatenate([train_dx[light_benign_idx], train_dx[medium_benign_idx] + 1]) # Add one so that we oversample medium_dx, will change back to 0
light_medium_paths, light_medium_dx, _, _ = oversample_minority(light_medium_paths, light_medium_dx)
medium_benign_paths = light_medium_paths[light_medium_dx == 1]

light_dark_paths = np.concatenate([train_imgs[light_benign_idx], train_imgs[dark_benign_idx]])
light_dark_dx = np.concatenate([train_dx[light_benign_idx], train_dx[dark_benign_idx] + 1])
light_dark_paths, light_dark_dx, _, _ = oversample_minority(light_dark_paths, light_dark_dx)
dark_benign_paths = light_dark_paths[light_dark_dx == 1]

light_benign_paths = train_imgs[light_benign_idx]
print(f"Oversampled light benign: {len(light_benign_paths)}")
print(f"Oversampled medium benign: {len(medium_benign_paths)}")
print(f"Oversampled dark benign: {len(dark_benign_paths)}")

# Make each dataset have the same number of malignant classes
light_malignant_idx = np.where((train_skin_tones == 0) & (train_dx == 1))[0]
medium_malignant_idx = np.where((train_skin_tones == 1) & (train_dx == 1))[0]
dark_malignant_idx = np.where((train_skin_tones == 2) & (train_dx == 1))[0]

medium_light_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[light_malignant_idx]])
medium_light_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[light_malignant_idx]])
medium_light_paths, medium_light_dx, _, _ = oversample_minority(medium_light_paths, medium_light_dx)
light_malignant_paths = medium_light_paths[medium_light_dx == 0]

medium_dark_paths = np.concatenate([train_imgs[medium_malignant_idx], train_imgs[dark_malignant_idx]])
medium_dark_dx = np.concatenate([train_dx[medium_malignant_idx] - 1, train_dx[dark_malignant_idx]])
medium_dark_paths, medium_dark_dx, _, _ = oversample_minority(medium_dark_paths, medium_dark_dx)
dark_malignant_paths = medium_dark_paths[medium_dark_dx == 0]

medium_malignant_paths = train_imgs[medium_malignant_idx]
print(f"Oversampled medium malignant: {len(light_malignant_paths)}")
print(f"Oversampled medium malignant: {len(medium_malignant_paths)}")
print(f"Oversampled dark malignant: {len(dark_malignant_paths)}")

# Combine the datasets
benign_paths = np.concatenate([light_benign_paths, medium_benign_paths, dark_benign_paths])
benign_dx = np.zeros(len(benign_paths))
malignant_paths = np.concatenate([light_malignant_paths, medium_malignant_paths, dark_malignant_paths])
malignant_dx = np.ones(len(malignant_paths))
benign_skin_tones = np.concatenate([np.zeros(len(light_benign_paths)), np.ones(len(medium_benign_paths)), np.ones(len(dark_benign_paths)) * 2])
malignant_skin_tones = np.concatenate([np.zeros(len(light_malignant_paths)), np.ones(len(medium_malignant_paths)), np.ones(len(dark_malignant_paths)) * 2])

train_imgs = np.concatenate([benign_paths, malignant_paths])
train_dx = np.concatenate([benign_dx, malignant_dx])
train_skin_tones = np.concatenate([benign_skin_tones, malignant_skin_tones])

assert(len(train_imgs) == len(train_dx) == len(train_skin_tones))

with open('/content/drive/MyDrive/Thesis/swin_oversample_adversarial.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)

  # header
  writer.writerow(["Lambda", "Fold", "Precision", "Recall", "F1", "PR-AUC",
                   "Light Precision", "Light Recall", "Light F1", "Light PR-AUC",
                   "Medium Precision", "Medium Recall", "Medium F1", "Medium PR-AUC",
                   "Dark Precision", "Dark Recall", "Dark F1", "Dark PR-AUC",])

  image_processor = AutoImageProcessor.from_pretrained(model_name)
  train_transform, val_transform = preprocess(image_processor)
  train_ds = AdversarialSkinLesionDataset(train_dx, train_skin_tones, train_imgs, transform=train_transform)
  val_ds = AdversarialSkinLesionDataset(val_dx, val_skin_tones, val_imgs, transform=val_transform)

  model = SwinModelWithAdversarial(model_name, lambda_=0.03)

  # Train the model
  training_args = TrainingArguments(
      output_dir="./trains",
      per_device_train_batch_size=64,
      per_device_eval_batch_size=64,
      eval_strategy="epoch",
      save_strategy="epoch",
      logging_strategy="epoch",
      num_train_epochs=10,
      learning_rate=1e-5,
      save_total_limit=2,
      remove_unused_columns=False,
      load_best_model_at_end=True,
      metric_for_best_model="pr_auc",
      greater_is_better=True,
      dataloader_num_workers=8,
      dataloader_pin_memory=True,
      fp16=torch.cuda.is_available(),
      report_to="none",
      disable_tqdm=False,
  )

  trainer = AdversarialTrainer(
      model=model,
      args=training_args,
      train_dataset=train_ds,
      eval_dataset=val_ds,
      compute_metrics=compute_metrics
  )

  # Get the results on the validation dataset
  trainer.train()
  eval_results = trainer.evaluate()

  val_results = trainer.predict(val_ds)
  val_pred = np.argmax(val_results.predictions[0], axis=1)
  val_dx = np.array(val_dx)

  equal_opportunity = equal_opportunity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
  demographic_parity = demographic_parity_difference(val_dx, val_pred, sensitive_features=val_skin_tones)
  equalized_odds = equalized_odds_difference(val_dx, val_pred, sensitive_features=val_skin_tones)

  # Failsafe in case the runtime breaks
  print(eval_results)

  writer.writerow([
    model_name,
    eval_results.get("eval_precision"),
    eval_results.get("eval_recall"),
    eval_results.get("eval_f1"),
    eval_results.get("eval_pr_auc"),
    equal_opportunity,
    equal_opportunity,
    demographic_parity,
    equalized_odds
  ])

Requirement already satisfied: fairlearn in /usr/local/lib/python3.12/dist-packages (0.13.0)
Requirement already satisfied: narwhals>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.19.0)
Requirement already satisfied: numpy>=1.24.4 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.0.2)
Requirement already satisfied: pandas>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (2.2.2)
Requirement already satisfied: scikit-learn>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.6.1)
Requirement already satisfied: scipy<1.16.0,>=1.9.3 in /usr/local/lib/python3.12/dist-packages (from fairlearn) (1.15.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.3->fairlearn) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.2.1->fairlearn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.3->fairlearn) (1.17.0)
Getting ISIC...
Getting MILK...
Number images with skin tone 0: 2866
Number images with skin tone 1: 7184
Number images with skin tone 2: 184
Combining Datasets...
Oversampled light benign: 4151
Oversampled medium benign: 4151
Oversampled dark benign: 4151
Oversampled medium malignant: 4447
Oversampled medium malignant: 4447
Oversampled dark malignant: 4447

The image processor of type `ViTImageProcessor` is now loaded as a fast processor by default, even if the model checkpoint was saved with a slow processor. This is a breaking change and may produce slightly different outputs. To continue using the slow processor, instantiate this class with `use_fast=False`.

Loading weights:   0%|          | 0/233 [00:00<?, ?it/s]

SwinForImageClassification LOAD REPORT from: microsoft/swin-tiny-patch4-window7-224
Key               | Status   |
------------------+----------+----------------------------------------------------------------------------------------
classifier.bias   | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000]) vs model:torch.Size([2])
classifier.weight | MISMATCH | Reinit due to size mismatch ckpt: torch.Size([1000, 768]) vs model:torch.Size([2, 768])

Notes:
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.

Adv pred counts: [ 964 1499 1572]
Adv true counts: [1713 2061  261]
Adv pred counts: [1069 1469 1497]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 812 1682 1541]
Adv true counts: [1713 2061  261]
Adv pred counts: [2257  171 1607]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 521 2006 1508]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 466 2536 1033]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 499 1848 1688]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 282 1120 2633]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 245  628 3162]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 231  411 3393]
Adv true counts: [1713 2061  261]

Adv pred counts: [ 231  411 3393]
Adv true counts: [1713 2061  261]
Adv pred counts: [ 231  411 3393]
Adv true counts: [1713 2061  261]
{'eval_loss': 9.611159324645996, 'eval_accuracy': 0.8780669144981412, 'eval_precision': 0.8553696708041014, 'eval_recall': 0.8761746821448314, 'eval_f1': 0.8656471873293282, 'eval_pr_auc': 0.9134755974799472, 'eval_adv_accuracy': 0.08872366790582403, 'eval_runtime': 21.2951, 'eval_samples_per_second': 189.48, 'eval_steps_per_second': 3.005, 'epoch': 10.0}

# Quantization

Load Swin Weights without Adversarial Model

In [ ]:
import os
import torch
from transformers import AutoImageProcessor, SwinForImageClassification

path = "/content/drive/MyDrive/Thesis/models/swin_adversarial_0.03"
base_model_name = "microsoft/swin-tiny-patch4-window7-224"

model = SwinForImageClassification.from_pretrained(
    base_model_name,
    num_labels=2,
    ignore_mismatched_sizes=True
)
processor = AutoImageProcessor.from_pretrained(path)

state_path_bin = os.path.join(path, "pytorch_model.bin")
state_path_safe = os.path.join(path, "model.safetensors")

if os.path.exists(state_path_bin):
    state_dict = torch.load(state_path_bin, map_location="cpu")
elif os.path.exists(state_path_safe):
    from safetensors.torch import load_file
    state_dict = load_file(state_path_safe)
else:
    raise FileNotFoundError("No pytorch_model.bin or model.safetensors found")

if "state_dict" in state_dict and isinstance(state_dict["state_dict"], dict):
    state_dict = state_dict["state_dict"]
elif "model_state_dict" in state_dict and isinstance(state_dict["model_state_dict"], dict):
    state_dict = state_dict["model_state_dict"]

mapped_state = {}

for k, v in state_dict.items():
    if k.startswith("model.swin."):
        new_k = k.replace("model.swin.", "swin.", 1)
        mapped_state[new_k] = v
    elif k.startswith("model.classifier."):
        new_k = k.replace("model.", "", 1)   # -> classifier.weight / classifier.bias
        mapped_state[new_k] = v

missing, unexpected = model.load_state_dict(mapped_state, strict=False)

print("Missing keys:", missing)
print("Unexpected keys:", unexpected)

# model.eval()

Some weights of SwinForImageClassification were not initialized from the model checkpoint at microsoft/swin-tiny-patch4-window7-224 and are newly initialized because the shapes did not match:
- classifier.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([2]) in the model instantiated
- classifier.weight: found shape torch.Size([1000, 768]) in the checkpoint and torch.Size([2, 768]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Missing keys: []
Unexpected keys: []

Convert to Onnx

In [ ]:
!pip install onnx onnxscript
!pip install optimum[onnxruntime]
from optimum.onnxruntime import ORTModelForImageClassification

save_dir = "/content/drive/MyDrive/Thesis/models/swin"
model.save_pretrained(save_dir)
processor.save_pretrained(save_dir)

onnx_model = ORTModelForImageClassification.from_pretrained(
    save_dir,
    export=True,
)

onnx_model.save_pretrained("/content/drive/MyDrive/Thesis/models/swin_onnx")

Requirement already satisfied: onnx in /usr/local/lib/python3.12/dist-packages (1.21.0)
Requirement already satisfied: onnxscript in /usr/local/lib/python3.12/dist-packages (0.6.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.12/dist-packages (from onnx) (2.0.2)
Requirement already satisfied: protobuf>=4.25.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (5.29.6)
Requirement already satisfied: typing_extensions>=4.7.1 in /usr/local/lib/python3.12/dist-packages (from onnx) (4.15.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx) (0.5.4)
Requirement already satisfied: onnx_ir<2,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from onnxscript) (0.2.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from onnxscript) (26.0)
Requirement already satisfied: sympy>=1.13 in /usr/local/lib/python3.12/dist-packages (from onnx_ir<2,>=0.1.15->onnxscript) (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13->onnx_ir<2,>=0.1.15->onnxscript) (1.3.0)
Requirement already satisfied: optimum[onnxruntime] in /usr/local/lib/python3.12/dist-packages (2.1.0)
Requirement already satisfied: transformers>=4.29 in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (4.57.6)
Requirement already satisfied: torch>=1.11 in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (2.10.0+cpu)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (26.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (2.0.2)
Requirement already satisfied: huggingface_hub>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (0.36.2)
Requirement already satisfied: optimum-onnx[onnxruntime] in /usr/local/lib/python3.12/dist-packages (from optimum[onnxruntime]) (0.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (1.4.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.8.0->optimum[onnxruntime]) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnxruntime]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnxruntime]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnxruntime]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11->optimum[onnxruntime]) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnxruntime]) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnxruntime]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.29->optimum[onnxruntime]) (0.7.0)
Requirement already satisfied: onnx in /usr/local/lib/python3.12/dist-packages (from optimum-onnx[onnxruntime]; extra == "onnxruntime"->optimum[onnxruntime]) (1.21.0)
Requirement already satisfied: onnxruntime>=1.18.0 in /usr/local/lib/python3.12/dist-packages (from optimum-onnx[onnxruntime]; extra == "onnxruntime"->optimum[onnxruntime]) (1.24.4)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.18.0->optimum-onnx[onnxruntime]; extra == "onnxruntime"->optimum[onnxruntime]) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.18.0->optimum-onnx[onnxruntime]; extra == "onnxruntime"->optimum[onnxruntime]) (5.29.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11->optimum[onnxruntime]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11->optimum[onnxruntime]) (3.0.3)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx->optimum-onnx[onnxruntime]; extra == "onnxruntime"->optimum[onnxruntime]) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnxruntime]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnxruntime]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnxruntime]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub>=0.8.0->optimum[onnxruntime]) (2026.2.25)

Quantize ONNX

In [ ]:
from optimum.onnxruntime import ORTQuantizer
from optimum.onnxruntime.configuration import AutoQuantizationConfig

onnx_dir = "/content/drive/MyDrive/Thesis/models/swin_onnx"
quantized_dir = "/content/drive/MyDrive/Thesis/models/swin_onnx_int8"

quantizer = ORTQuantizer.from_pretrained(onnx_dir)

qconfig = AutoQuantizationConfig.arm64(
    is_static=False,
    per_channel=False,
)

quantizer.quantize(
    save_dir=quantized_dir,
    quantization_config=qconfig,
)

WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.0/blocks.0/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__12"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.0/blocks.1/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__76"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.1/blocks.0/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__578"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.1/blocks.1/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__641"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.0/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__1143"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.1/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__1206"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.2/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__1694"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.3/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__1757"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.4/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__2245"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.2/blocks.5/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__2308"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.3/blocks.0/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__2810"
    }
    dim {
      dim_value: 2
    }
  }
}
.
WARNING:root:Inference failed or unsupported type to quantize for tensor '/swin/encoder/layers.3/blocks.1/Slice_output_0', type is tensor_type {
  elem_type: 7
  shape {
    dim {
      dim_param: "unk__2873"
    }
    dim {
      dim_value: 2
    }
  }
}
.

PosixPath('/content/drive/MyDrive/Thesis/models/swin_onnx_int8')